xapi-project/xenopsd

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

This relies on qemu traditional understanding the Xenstore key.
There is no PV floppy support.
libxl doesn't support floppies either.
Requires:
- [xapi-project/xcp-idl#46]

[RFC] xc: support floppy disk images

---

lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_skeleton.ml
simulator/xenops_server_simulator.ml
xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

Xapi delegates the xenstore operations to xenopsd.
Signed-off-by: Hui Zhang <hui.zhang@citrix.com>

CP-10203: XenAPI: api call for RDP on/off request

---

xl/xenops_server_xenlight.ml

The async version was failing part of the way through with a timeout,
after killing the qemu but before killing the domain.
The synchronous version seems to work ok.

CA-159588: use synchronous libxl domain destroy rather than async

---

lib/xenops_hooks.ml
lib/xenops_server.ml

These hooks are necessary in environments where post-VM start operations
are needed, such as setup of VM firewall rules

Add hooks for post-resume and post-migrate

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

Pass the appropriate flags to QEMU when the IGD_passthrough video type is specified.  Depends on changes to xcp-idl and xapi.

CP-10125: Pass IGD passthrough arguments through to QEMU

---

xl/xenops_server_xenlight.ml

We also have
- backend-kind=qdisk: qemu qdisk
- backend-kind=vbd3: tapdisk3
Signed-off-by: David Scott <dave.scott@citrix.com>

libxl: we use 'backend-kind=vbd' to mean 'blkback'

---

xc/domain.ml
xc/domain.mli
xc/xenctrlext.ml
xc/xenctrlext.mli
xc/xenctrlext_stubs.c

This is dead code, not called by anything high-level in xenopsd.

Remove unused trigger_power and trigger_sleep functions

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

The storage backends should choose the default datapath for a given
VDI, which could be: tapdisk3, blkback or even qdisk.
This patch extends the existing 'backend-kind' mechanism to allow an
SMAPIv1/2 backend to return a choice via the 'xenstore_data'. This is
a port of the existing libxl mechanism in c/s 8fb7bcb4

CP-11511: allow storage backends to choose a datapath

---

xc/xenops_server_xen.ml

The SM backend can return a backend-kind in the attach_info:xenstore_data.
If the user knows what they are doing they can override this with
VBD.other_config. This user override mechanism is currently used by
the RawHBA SR. This patch fixes it by removing a duplicate definition of
"kind".
I'm still testing this, so don't merge yet.

CA-165131: fix the backend-kind override mechanism

---

xc/xenops_server_xen.ml

This reverts commit b0b2e425637f9facc2a06fe812ec3dbb32c52ce9.
This option is no longer needed with the new demu

Revert "Use only -std-vga for Qemu when using dummy vGPU"

---

test/test.ml
xc/domain.ml
xc/domain.mli
xc/stubdom.ml
xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

Add bool VM.auto_update_drivers (DynamicRO) to replace the usage of pci_pv in VM.platform
Add key: "/local/domain/%d/control/auto-update-drivers" for new field
Signed-off-by: chengz <cheng.zhang@citrix.com>

CP-12148:  Replace platform: pci_pv to new field auto_update_drivers

---

scripts/block

If the `params` comes back as `/dev/mapper/foo` then we might
discover that this is a relative symlink like `../dm-1`. We need
to pass `stat` a full path, so we need to canonicalise to something
like `/dev/dm-1`.
Signed-off-by: David Scott <dave.scott@citrix.com>

scripts/block: use `readlink -f` to canonicalise paths

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

Device.PCI.list relies on this key being present - without it, plugged PCIs will be reported to xapi as unplugged.

CA-173686: Write passed-through PCI's address to xenstore

---

lib/storage.ml
lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_skeleton.ml
simulator/xenops_server_simulator.ml
xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

The Vbd metadata from xapi says whether we want to open the
device in persistent mode or not. We pass this along to the
SMAPIv2 layer via `VDI.epoch_begin`.
This depends on [xapi-project/xcp-idl#83]

VDI.epoch_begin now takes a `persistent` argument

---

lib/path.ml
xc/device.ml

When switching an Intel GPU from GVT-g mode to passthrough mode, simply unbinding the device from the i915 driver isn't enough - we need to rmmod the i915 module completely. Consequently we need to modprobe the i915 driver when switching back to GVT-g mode.

CP-12982: Changes for i915 driver binding/unbinding

---

xc/device.ml
xc/device.mli
xc/domain.ml
xc/xenops_server_xen.ml

This xl pci-attach and pci-detach are working now and this
patch makes xenopsd-xc to use them.
Also removing some dead code paths
Signed-off-by: Koushik Chakravarty <koushik.chakravarty@citrix.com>

CA-168029: Using xl pci for plug/unplug in xenopsd-xc

---

xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

Work around strange behaviour in the OCaml xenstore client library so that
VM.get_state doesn't try to read invalid paths from xenstore, each of which is
guaranteed to result in EINVAL from xenstored. This behaviour causes unnecessary
load on xenstore.
The behaviour is as follows. Consider the following xenstore tree:
/local/domain/1/dir0 = ""
/local/domain/1/dir0/key0 = "a"
/local/domain/1/dir0/key1 = "b"
/local/domain/1/key1 = "c"
Here's the behaviour of two xenstore commands:
1. xs.Xs.directory "/local/domain/1/dir0"
-> ["key0"; "key1"]
2. xs.Xs.directory "/local/domain/1/key1"
-> [""]
Perhaps more appropriate behaviour would be to return [] in the second example.
But the existing [""] behaviour means that xenopsd's ls_lR function thinks that
there's a sub-directory called "", so tries …

CA-187017: VM.get_state: don't try to recurse into non-directories in xenstore

---

lib/xenops_server.ml

When importing VM metadata that was sent to us by a xenopsd running on another
host (e.g. during a live migration), we need to ensure that the VM has a valid
featureset configured in its platformdata.
If platformdata does not contain a featureset, then we are importing a VM that
comes from a levelling-v1 host. In this case, give it a featureset that
contains all features that this host has to offer.

Support migration from pre-levelling-v2 hosts

---

xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

According to the Xen header SHUTDOWN_watchdog indicates the domain
should be restarted due to the watchdog timing out.
Signed-off-by: Simon Rowe <simon.rowe@eu.citrix.com>

Treat watchdog (4) the same as reboot(1)

---

xc/domain.ml
xc/xenops_server_xen.ml

Xenctrl.Halt has always been incorrect in the libxc bindings (and should have
been Watchdog).  This was fixed upstream in
http://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=87a16694248e80195943741bb9f857edd6a6bf51,
but subsequently causes a compilation error in xenopsd.
Instead of shutting the domain down with a Watchdog signal, use the correct
Poweroff instead.
Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>

Correct the use of Xenctrl.Halt

---

xc/domain.ml
xl/xenops_server_xenlight.ml

On domain creation, after creating xenstore node "/domain/N/device",
now we create nodes under it for a list of kinds of device:
[ "vbd"; "vif"; "vfb"; "vkb"; "vfs"; "pci" ]
This is needed now for the VIF and VBD drivers in Windows guests, but
may well be wanted for other guests and device-kinds in the future.

CP-15276: Create xenstore nodes device/[vbd,vif] etc.

---

xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

Watch the xenstore subtree based at /local/domain/N/feature
and include it in the "guest_agent" assoc-list that is part
of the state value returned by VM.stat.
This subtree is where guests should announce their support
(or lack of it) for various features.

CP-15277: copy "feature" xenstore tree for VM.stat

---

xc/domain.ml
xl/xenops_server_xenlight.ml

Add "/domain/N/feature" to the list of nodes that we create (with
read-write permission for the guest) on creation of domain N.
This will be used by the guest to announce whether it
supports various features, for example by writing 1 or 0
to /domain/N/feature/hotplug/vbd to indicate whether or
not it supports vbd hotplug.

CP-16049: create rw xenstore node "feature" for guest

---

lib/xenops_server.ml

Before this patch there was a hole in the exception handling where the
newly-created destination domain wouldn't be cleaned up if the VM_restore into
it failed but it would if later operations failed.
This patch unifies the error handling in VM_receive_memory so that it always
cleans up the domain it creates on failure.

CA-195652: Cleanup new domain on VM_receive_memory failure

---

xc/domain.ml
xl/xenops_server_xenlight.ml

At start of day these are required for the guest to advertise the
ability to hotplug VIFs and VBDs and their creation by the toolstack is
outlined in the Xen docs: "Xenstore paths for hotplug features"[1].
When support was originally added for this in commit e894ebfd, it also
created vfb, vkb, vfs and pci nodes under the guest's device tree. At
least the first two of these are problematic and cause the guest's
console to be redirected incorrectly.
This patch removes the four additional Xenstore nodes from the guest
that were only added originally for symmetry.
[1]: http://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=e8f98cb2

CA-197635: Only create vif/vbd device guest Xenstore entries

---

lib/xenops_server.ml
lib/xenops_task.ml
lib/xenops_utils.ml
xc/xenops_server_xen.ml

such as vm-start, vm-shutdown, vm-restore, vm-poweroff, vm-reboot.
In this patch, a new composable Parallel atom in xenopsd is created. Any
atoms inside Parallel will be executed concurrently in a new independent
pool of worker threads specific for the Parallel atoms. A new pool of
parallel worker threads is used to avoid a deadlock where an operation
needs to wait for a Parallel atom to run but the Parallel atom cannot run
because all the default worker thread slots are being used by other
operations also waiting for Parallel atoms to run.
The Parallel atom is used to execute in parallel all the VBD-related atoms
that are otherwise taking a long time to execute as a sequence during the
VM lifecycle operations, which are:
VBD.epoch_begin
VBD.plug
VBD.unplug
VBD.epoch_end
The SM layer …

CA-184556: call VBD actions in parallel to speed up VM lifecycle operations

---

lib/xenops_server.ml

otherwise the inner mutex n will not be unique and therefore will
not protect against concurrent accesses.

CA-201166: Redirector.pop must not be a function

---

lib/xenops_utils.ml
xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

Currently, xenopsd exports large chunks of xenstore to xapi so that it can deduce whether VMs have PV drivers loaded.
Instead, let xenopsd work this out for itself by watching the relevant "state" fields in xenstore. Overall this causes much less xenstore traffic to be generated, especially for VMs with several VBDs or VIFs.
Measurements show that this leads to a 95% reduction in the time taken to sequentially start 256 VMs (8 VBDs per VM).

CA-203169: determine whether PV drivers are detected

---

xc/hotplug.ml

These keys are already cleaned up when the VM shuts down, but not on unplug.

Clear private xenstore data on VIF unplug

---

xc/device.ml
xc/device.mli
xc/device_common.ml
xc/domain.ml
xc/hotplug.ml
xc/xenops_helpers.ml
xc/xenops_server_xen.ml

There can be multiple domains for a single VM during a localhost migration, and
the private data path is indexed by UUID, not domid. When unplugging the
devices for the old domain during a localhost migration, we must not remove the
private data keys, because they are needed by the new domain.

CA-209511: Don't remove private data path for devices during localhost migration

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

Until now we have been defaulting the keymap to `en-us` but this
prevents VNC clients from using the QEMU ExtendedKeyEvent extension for
passing raw scan codes.
If a keymap is not passed to QEMU, it will default to using `en-us`
anyway but will enable the ExtendedKeyEvent extension.
This does not change the behaviour for when a keymap has actually been
specified. In this case, it is still honoured and passed to QEMU with
the `-k` option.

CP-17631: Don't use a default QEMU keymap

---

scripts/qemu-dm-wrapper
xc/device.ml

The stderr and stdout output from the device model process (QEMU) should be
logged so problems with starting the device model (before it can setup
syslog logging) can be diagnosed.

CP-17694: Log stdout/stderr from device model

---

xc/device.ml
xc/device_common.ml
xc/device_common.mli
xc/xenops_server_xen.ml

The change will update the sm-data xenstore keys (under the VBD's backend path) in case when the underlying CD being injected or ejected. This is good for consistency, and more importantly, a necessity for other components that watch these fields for a purpose (e.g rrdd's iostats plugin).

CA-213992: update sm-data as part of HVM media insert/eject

---

xc/xenops_server_xen.ml

The comment on top of the `VBD.unplug` function says:
1. if the device has already been shutdown and deactivated (as in suspend) we
must call DP.destroy here to avoid leaks
However, recent commit d723d4b0 had regressed this.

CA-217921: VBD.unplug must destroy the datapath if a VBD was already shut down

---

lib/platform.ml
lib/platform.mli
lib/xenops_utils.ml
xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

These values are initialised from the VM's platformdata. A new module `platform.{ml,mli}` contains an interpretation of platform values that matches  the one used by Xen API (in vm_platform.ml).
The context of this PR is that we want to give XAPI access to the platform flags from the time when a VM first boots. This is used to decide about permissions of migration operations later in the life of a VM. Only xenopsd knows about these flags and we communicate them to Xapi using xcp-idl.

CP-18289 add booleans to VM state: nomigrate, nested_virt

---

xc/xenops_server_xen.ml

There is now a spec of how the shutdown protocol should work:
http://xenbits.xen.org/gitweb/?p=xen.git;a=blob;f=docs/misc/xenstore-paths.markdown#l378
This patch changes xenopsd to prefer the `poweroff` shutdown command
over the `halt` command, but only when the guest advertises
`feature-poweroff`. Note that libxl has used `poweroff` exclusively
for several years now:
http://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=79e162885078a9daaaf9679d547aaa65c78e3559

CA-217805: Prefer asking newer guests to poweroff rather than halt

---

xc/xenops_server_xen.ml

Since this is an update to a VIF or VBD, the usual logic only causes
an update for the relevant device. Thus xapi didn't know to look at
the VM again, and hence might not update the pv_drivers_detected
field. This commit adds an explicit update to the VM if the
pv_drivers_detected field changes from false to true.

CA-219763: If the PV drivers have been detected, raise an update

---

xl/xenops_server_xenlight.ml

Although AFAICT there's no way to use it.

CP-18404: Add force option to xenlight backend too

---

lib/xenops_utils.ml
xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

When updating the MTU of a VIF it can happen that the VM `domid` is still out of sync. We can use the correct `domid` value passing it via `xenopsd` as a field in `VIF.stat`.
See also https://github.com/xapi-project/xcp-idl/pull/131

[CP-18781] Add device information in VIF.state

---

xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

`ionice` errors happens when the VBD qos are unset (the default), marking them as warnings allows us to remove a lot of spurious errors from the logs.

CA-203423: fail to parse ionice, error -> warn

---

scripts/setup-pvs-proxy-rules

As otherwise xe pvs-proxy-destroy fails on running VMs as follows:
[root@xrtuk-16-04 ~]# xe pvs-proxy-destroy uuid=8d484722-ca9c-487e-b826-f8defa58925b
The server failed to handle your request, due to an internal error.  The given message may give details useful for debugging the problem.
message: xenopsd internal error: Forkhelpers.Spawn_internal_error("/usr/libexec/xenopsd/setup-pvs-proxy-rules: line 197: XSRM: command not found\n", "", _)
Signed-off-by: Robert Breker <robert.breker@citrix.com>

CA-225257: Fix XSRM typo in setup-pvs-proxy-rules

---

scripts/qemu-dm-wrapper

This avoids the need to rely on the cgrulesengd daemon to move the process into
its designated slice. This daemon fails to do its job if it takes too long to
write to the tasks file. On a 4.4 kernel, it can take several milliseconds to
write to this file, so that kind of failure is very likely.
Signed-off-by: Jonathan Davies <jonathan.davies@citrix.com>

CA-225067: move qemu-dm to default cgroup slice

---

xc/xenops_server_xen.ml
xl/xenops_server_xenlight.ml

This commit fixes a typo in the "nested-virt" platform key that is
tracked by xenopsd and reported to Xapi.

CA-225775 fix typo in platform key: nested-virt (was: nested_virt)

---

scripts/setup-vif-rules

This now includes VIFs that have `locking_mode=disabled`, because leaving the
interface down can cause VMs that are shutting down to hang.

CA-225971: Bring up all netback devices, regardless the locking mode

---

scripts/setup-pvs-proxy-rules
scripts/vif-real
xc/device_common.ml
xc/device_common.mli
xc/hotplug.ml
xc/xenops_server_xen.ml

Localhost migration failed, because the vif-real and setup-pvs-proxy-rules
scripts use xenstore keys to pass information between each other and xenopsd,
but the keys were in the VM-UUID-based private tree. During a localhost
migration, the sender writes keys that are soon after removed by the receiver.
We solve this by moving the xenstore keys from the private path to the hotplug
path, which is indexed by domid.

CA-223506: setup-pvs-proxy-rules: handle localhost migration

---

scripts/setup-vif-rules

This was previously achieved by bringing down the netback device, but that
turned out to be problematic (see 1e0eb8734849186ca3f2d8be12dd6f6e5a36f1e7).

CA-226099: setup-vif-rules: drop all traffic on disabled VIFs

---

xc/xenops_server_xen.ml

Add missing fix for CA-92842.
Signed-off-by: Sharad Yadav <sharad.yadav@citrix.com>

CA-227101: Increase timeout from 0 to 60 seconds when squeezing domains.

---

scripts/setup-pvs-proxy-rules

The problem is that we used the wrong PVS site UUID: xenopsd was using the one from the sending pool, while xapi was using the one from the present (destination) pool.
The fix changes `setup-pvs-proxy-rules` to look for any `/xapi/pvs-proxy/*/$VIF/state` (where `$VIF` is the VIF UUID). The VIF UUID is maintained across the migration and that a proxied VIF can be in only one PVS site at once.
This was tested by attempting cross pool migrations of PVS-cached VMs between two pools (I first reproduced the bug with the old script and then observed that it did not happen again with the new version).

CA-227626: pvsproxy is not caching data for VM following cross pool migration 

---

scripts/setup-pvs-proxy-rules

Ticket title: VM not cached after start/resume in PVS Stress tests -
missing OVS rules for intercepting traffic.
In the previous update (CA-227626) we used `xenstore-ls` to get the
appropriate path for the proxy state. This fails if a key is removed
from xenstore while reading. This patch swaps `xenstore-ls` with the
safer `xenstore-list` at the price of a slightly more complicated code.

CA-227605: issues with PVS caching under stress tests

---

scripts/setup-pvs-proxy-rules

The check on signed contained a typo that made it pass some tests but
failed on more careful ones.

CA-227605: fix inconsistent check in the CA-227605 patch

---

xc/device.ml

The function `Device.Vbd.media_is_ejected` is meant to return `true` if there is no CDROM present in the given drive, represented by a VBD, and `false` if there is. If the VBD is not plugged, it would also return true. This can cause its caller, `Xenops_server_xen.VBD.get_state`, to return an VBD state as "plugged with an empty drive" rather than "unplugged", if the `get_state` call comes in while the VBD is being unplugged.
This was seen during a VM reboot, where it caused xapi to interpret the VBD state and mark the drive as empty in its database. This meant that the VM had a CDROM in its drive before the reboot, but no longer after the reboot.
This patch makes `media_is_ejected` raise an exception if the VBD is unplugged, such that `get_state` always returns an "unplugged" VBD state. …

CA-234037: Fix race in CDROM status checking

---

xc/device.ml
xc/xenops_server_xen.ml

Not yet passing -mxgpu-sched-level because of the current state of
qemu and the gim kernel module.

CP-20431: MxGPU: pass -mxgpu-fb-size to qemu

---

xc/device.ml

The FB size will need to be passed to gimtool as part of
CP-21148 but qemu does not recognise this option now, so
we must stop passing it to qemu in order to start VMs
Signed-off-by: Bob Ball <bob.ball@citrix.com>

CP-21275: Don't pass FB size to qemu

---

xc/device.ml
xc/device_common.ml
xc/device_common.mli
xc/domain.ml
xc/xc_resources.ml

This is to initialise the pGPU for the vGPU type that will be run on it. The
call may only be done when there are no vGPUs running on the given pGPU yet,
and we do some accounting in xenstore to keep track of the running vGPUs.

CP-21148: Call gimtool when starting the first MxGPU VM on a pGPU

---

xc/domain.ml
xc/xenops_server_xen.ml

(A) Originally, Xenops_server_xen.VM.run_script bundles in one transaction:
(1) read state from XenStore
(2) do nothing, raise exception, or remove path in XenStore
(3) write two paths in XenStore
This commit limits the transaction to writing the two paths in XenStore
in (3) but takes (1) and (2) out of it. This is safe:
* The state read in (1) is acted upon but the writes in (3) have no data
or control dependency on the state being written.
* The path being removed in (2) is expected not to exist in the first
place. Now, if the state indicates it does exist and (2) is reached to
remove it, the only thing that could happen in between is that it
is already removed. No harm is done when trying to remove it again. In
fact, it would be safe to remove the path unconditionally.
* The two writes …

Ca 248130 eliminate one xenstore transaction, reduce another to write ops

---

_tags

This slipped by mistake in the latest cleanup PR

Remove coverage from default build tags

---

.travis.yml

This will get the new xenopsd Ely lcm branch (0.17-lcm) working with Travis by using the RPMs from Ely instead of master.

Update .travis.yml: Build against Ely

---

opam

Forgot to update `opam` file in my coverage PR, sorry about the breakage.
This fixes the build/install part of an `opam` install.
`opam remove` complains, but that seems to have been a problem previously as well:
```
```
I dropped the `--disable-libvirt` flag because it is not supported anymore and configure was rejecting it.

fix opam: setup.ml is now a generated file

---

lib/xenops_server.ml

We do it by mocking `perform_atomics_and_wait`. We cannot use that specific
function because we are delaying an `operation` and not an `atomic`.

CA-254911: delay shutdown cleanup actions to mitigate a potential stack overflow

---

lib/xenopsd.ml
xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

The HVM guest is very likely to hang or crash when qemu crashes, but the VM                                                                                           
will usually stay running until a force shutdown is applied. This patch uses                                                                                           
the forkexecd waitpid facility in an asynchronous way to signal to xenopsd                                                                                           
that qemu crashed or ended unexpectedly after the VM started. A signal masking                                                                                           
system disables the signal if an expected domain destroy event is detected, to …

CP-17693: take action when qemu crashes or exits unexpectedly

---

xc/domain.ml

This is a temporary change, create and send xen-set-global-dirty-log
from xenopsd and once emu-manager can send the message, remove this code.

CP23043: Send xen-set-global-dirty-log from xenopsd

---

lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_simulator.ml
lib/xenops_server_skeleton.ml
lib/xenopsd.ml
xc/xenops_server_xen.ml
xenopsd.conf

This PR goes with:
- https://github.com/xapi-project/xcp-idl/pull/167
- https://github.com/xapi-project/xen-api/pull/3138
Before migration we balloon the memory down to dynamic_memory_min. On windows the driver can sometimes persist ballooning when xenopsd believes it has completed its job (also it can restart ballooning when additional memory gets freed). The ballooning driver ignores suspend requests and this can make the migration timeout leaving the vms in a bad state.
This mitigates the issue by monitoring the ballooning key in xenstore and issuing the suspend request only after it is done. It also adds a configurable timeout to cancel the migration if the additional ballooning is taking too long, raising an error that provides a meaningful suggestion in xapi (Increase the memory …

CA-259579: Introduce ballooning timeout before migration

---

xc/device.ml

When shutdown a VM, QEMU is killed before domain is down. Some test cases
will check domain status including VNC port, so save vnc port into xenstore
once got it.

CA-260220: Put vnc port into xenstore after querying

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

The original qemu-trad patch added as part of CP-9364 was split into two:
- a small upstream qemu patch that implements the xen platform io-port 0x10 and
collects the product-num and build-num for the PV driver, and exposes them via
the new query-xen-platform-pv-driver-info QMP command, see qemu.pg PR 34:
. CP-23471: Expose product number and build number of XEN PV driver
- this xenopsd patch, which collects product-num and build-num for the PV
driver using the QMP command above, and using the original algorithm in
qemu-trad, decides if the PV driver belongs to a HVM Linux guest. In this case,
it writes to xenstore as qemu-trad would have done, see qemu-trad.pg patches:
. CP-9364: write feature-flags to xenstore when HVM guest stops using
emulated devices
. CP-9364: xapi expects …

CP-22500: support clean suspend,shutdown etc for HVM Linux using upstream qemu

---

xc/device_common.ml

Originally, an error in Qmp_protocol.connect would cause xenopsd
tasks to fail. This would create a race condition, where tasks
would fail after qemu was killed and prevent specific signals
such as VM_check_state from being handled until the end, resulting
in VMs with inconsistent state.
This patch makes sure that in the event of a QMP connection error,
None is returned as expected.

CA-260353: return None if Qmp_protocol.connect raises error

---

lib/xenops_server.ml
xc/xenops_server_xen.ml

xenopsd was changed to send poweroff instead of halt for newer guests
with commit 7a71ef8ac5e8 ("CA-217805: Prefer asking newer guests to
poweroff rather than halt").  Unfortunately there are some existing
guests (NetScaler/FreeBSD 8.4) that actually do halt when asked to. This
is not correct because the toolstack has been told to shutdown the VM,
not halt it. This is only seen with upstream QEMU because qemu-trad had
a bug in the emulated serial controller that caused FreeBSD to go
straight from halt to shutdown so this halting behavior was never
noticed.
Since all known guests support being asked to poweroff, send this
instead of halt.

CA-262911: Use poweroff rather than halt

---

.travis-python-nosetests.sh
.travis.yml
Makefile
scripts/igmp_query_injector.py
scripts/test_igmp_query_injector.py

Implement a script for IGMP query injection.
It can 
- inject IGMP query to vifs with/without vif connection state checking & waiting
- inject IGMP query to vifs of specific bridges
- specify MAX_RESP_TIME field of IGMP query packet

CP-23605: Implement script to inject IGMP query

---

lib/resources.ml
scripts/qemu-dm-wrapper
xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

For Stage 1:
* Always use qemu-trad unless a VM is specifically set to
use one of the known profiles:
- qemu-trad
- qemu-upstream
- qemu-upstream-compat
* The device model profile used if VM.platform["device-model"] is
not set shall be 'qemu-trad' (the fallback)
* Each profile has its own device model wrapper.
* Remove unused global variables related to old qemu-trad wrapper.
(cc: @jonludlam, @robhoes, @lindig )

CP-23595: Introduce device model profiles to xenopsd - Stage 1

---

_oasis.in
opam
xc/device.ml

Create a qmp_event_thread to monitor QMP events of all QEMU-upstream domains and handle necessary events.
Also create a pipe as an extra fd, when a QEMU-upstream based HVM is started, write a character to the pipe to wake up qmp_event_thread.
We use Core.Linux_ext.Epoll in qmp_event_thread because it is already part of xs-opam.
Module Lookup is used to abstract two hashtables (fd to domainid and domain to qmp connection) in a single data structure that's easy to use.
Module Monitor is used to abstract epoll operations and filter input events.

CP-23986: Implement QMP event thread in xenopsd

---

xc/xenops_server_xen.ml

Commit 42bd3e76a1f5 ("CA-264906: Call new domctl for qemu-trad vCPU
hotplug") broke vCPU hotplug for PV domains because it always called the
new domctl but this domctl does not work with PV domains. Fix this by
only calling the new domctl for HVM domains.

CA-265618: Fix vCPU hotplug for PV domains

---

scripts/igmp_query_injector.py
scripts/test_igmp_query_injector.py

1. introduce `scapy` for packet generation
1.1 copy & crop code for IGMP layer generation
2. simplify logic about invoking the blocking call of xenstore watch
3. remove daemonize parameter `--detach` 
4. update unit test accordingly

CP-24270 Rework IGMP query injection script

---

xc/device.ml

The xenstore key '/libxl/<dom-id>/dm-version' is created by qemu-wrap
when starting QEMU-upstream, we need to clean up this after the domain
is destroyed.

CP-24468: Clean up libxl xenstore keys after qemu-wrapper

---

xc/device.ml

For QEMU-upstream, when receives RTC_CHANGE event, write the value to
xenstore path /vm/<uuid>/rtc/timeoffset, which will wakeup xenstore
watcher in xenops_server_xen to uptdate timeoffset.

CP-24090: Respond to RTC_CHANGE QMP message

---

xc/device.ml
xc/device.mli
xc/domain.ml
xc/xenops_server_xen.ml

With the introduction of upstream qemu, the xenopsd code was getting full of if-then conditions for upstream qemu, which was removing the modularity of the code, making it difficult in the future to remove the qemu-trad code.
This patch series adds an interface to handle code that has different behaviour between different device model profiles (eg. qemu-trad and qemu-upstream), so that we regain the modularity back and it's easier in the future to add more profiles.
Only the following functions that are currently using is_upstream_qemu() are affected by the series:
> xc/device.ml:608:    if is_upstream_qemu device.frontend.domid           -> Device.Vbd.qemu_media_change
> xc/device.ml:1611:    let is_upstream = is_upstream_qemu domid in        -> Device.Dm.get_vnc_port
> …

CP-24361: use abstract qemu interface to split code between trad/upstream qemu in xenopsd

---

xc/device.ml

The refactoring of the abstract qemu interface in xenopsd occurred at the same time as 4 patches were added to xenopsd, causing a merge conflict and requiring manual rebasing. 
This patch series rebases each of the conflicting patches.

CP-24361:  abstract qemu interface: rebase 4 conflicting patches

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

At the point where `init_daemon()` is called, qemu is not running yet, so it hasn't created the libxl key in xenstore that is used to distinguish between the qemu backends.
The main side-effect is that the `QMP_Event.add` function is not called when the upstream-qemu profile is used because the wrong backend for init_daemon() is selected.
This series addresses this problem by:
- improving the abstraction of the device-model parameter sent to init_daemon(), which was string and becomes Profile.t, in order to provide a robust type-safe parameter to select from.
- using Profile.t (instead of the libxl xenstored key) to select the correct backend for init_daemon()
- moving functions that depend on init_daemon() to the end of the Dm module.

CP-24361: use the profile to select the backend before running the qemu daemon

---

lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_simulator.ml
lib/xenops_server_skeleton.ml
lib/xenops_utils.ml
xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml
xl/xenops_server_xenlight.cppo.ml

To support usb passthrough feature, will use qemu to
add/del usb devices to vm.
1. Add vusbs to vm metadata.
2. Add VUSB VUSB_DB module.
3. Add VUSB_plug VUSB_unplug to atom operation.

CP-24744: Add VUSB plug/unplug

---

_oasis.in
lib/resources.ml
lib/xenops_server.ml
lib/xenopsd.ml
opam
scripts/qemu-dm-wrapper
xc/device.ml
xc/device.mli
xc/device_common.ml
xc/device_common.mli
xc/domain.ml
xc/xenops_server_xen.ml
xc/xenops_xc_main.ml

This PR merges branch qemu-stable into master. 
```
52dac0cc CA-267466: call QMP_Event initialisation in xenops_server_xen.init()
850935f7 CA-267466: define constant for '/var/run/xen' and qmp socket path
4ecc622f CA-267466: xenopsd does not reconnect to QMP events after xenopsd restart
d4ff5e12 CP-24361: use the profile to select the backend before running the qemu daemon
470f36b1 CP-24361: improve abstraction for dmpath parameter from string to Profile.t
6f39be21 CP-24361: use the qemu backends for init_daemon
77e3c136 CP-24361: abstract qemu interface: rebase patch CP-24090 d1cfa14 into qemu backends
fc98abb2 CP-24361: abstract qemu interface: rebase patch CP-24090 65b9975 into qemu backends
7b6a3fa0 CP-24361: abstract qemu interface: rebase patch CP-24468 9b81674 into qemu backends …
```

Merge support for qemu-upstream into master

---

xc/device.ml

There are two qemu-upstream profiles, and each was creating its own                                                                                           
upstream-qemu QMP_Event thread. Instead, we should have only a single                                                                                           
QMP_Event thread.                                                                                                       
This patch replaces the `Q.Dm.Event.init()` call for each profile in favour of a                                                                                           
single static `Qemu_upstream.Dm.Event.init()` call. In the future, we may return                                                                                           
to the …

CA-267466: create a single QMP_Event thread

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

This new event replaces the reliance on the xenops_server_xen.ml function `maybe_update_pv_drivers_detected` to detect the PV drivers connected state 4 event to decide when to set the HVM Linux feature flags in xenstore. Relying on the QMP event XEN_PLATFORM_PV_DRIVER_INFO to set the HVM Linux feature flags makes it completely backwards-compatible with qemu-trad.                                                                                           
The improvement above is also an opportunity to remove the public function `maybe_write_pv_feature_flags`, which was only added to permit it to be called from the function `maybe_update_pv_drivers_detected` in xenops_server_xen.ml. 
The last commit replaces the control/feature flags according to the xen upstream design …

CP-24774: use QMP event XEN_PLATFORM_PV_DRIVER_INFO to set HVM Linux feature flags

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

This PR introduces code to handle new QMP events for upstream QEMU and eliminates potential differences in behavior between qemu-trad and QEMU. This code is coming from the `qemu-upstream` branch and has been tested there.

CP-24774 CA-267954 handle new QMP events

---

xc/device.ml

We need to check the if qemu-upstream is used when plug vusb to vm.

CP-24744: Ensure vusb plug must use upstream qemu

---

lib/xenops_server.ml
xc/device.ml
xc/xc_resources.ml
xc/xenops_server_xen.ml

According to CP-24616. we need to reset usb device before pasthrough to vm.

 CP-25063: Reset USB device before passthrough

---

xc/domain.ml

When we don't have this key set to the actual console buffer
size limit xenconsoled tends to accumulate the guest console
output indefinitely if there are no clients to consume it in
Dom0. The problem manifests itself when "disable_pv_vnc"
parameter in other-config is set to 1 which means there are no
vncterm clients started for PV consoles.

CA-269046: add "console/limit" key to xenstore for a domain

---

scripts/qemu-wrapper
xc/device.ml
xc/device.mli
xc/stubdom.ml
xc/stubdom.mli
xc/xenops_server_xen.ml

I'm attaching results from dev testing. The lines are from /var/log/daemon.log with inserted line breaks for legibility.
Before the current changes these are the CLI options coming out of xenopsd:
```
Oct 30 14:00:15 localhost forkexecd: [ info|dt16|0 ||forkexecd] qemu-dm-4[30956]: Arguments: 4 --syslog -d 4 -m 2048 -boot cdn
-serial pty -vcpus 2 -std-vga -videoram 8 -vncunused -vnc 127.0.0.1:1 -usb -usbdevice tablet
-net nic,vlan=0,macaddr=ce:f2:af:5f:a6:e2,model=rtl8139 -net tap,vlan=0,bridge=xenbr0,ifname=tap4.0
-net nic,vlan=1,macaddr=fa:61:82:f5:d3:8a,model=rtl8139 -net tap,vlan=1,bridge=xenbr0,ifname=tap4.1
-net nic,vlan=2,macaddr=9e:2b:92:31:76:a5,model=rtl8139 -net tap,vlan=2,bridge=xenbr0,ifname=tap4.2
-net nic,vlan=3,macaddr=d6:23:c8:d1:08:2a,model=rtl8139 -net …
```

CP-24771: Moved CLI network options from qemu-wrapper to xenopsd.

---

xc/device.ml
xc/device_common.ml

According to the design, xenopsd shall send the `stop` QMP message to stop QEMU before sending the `xen-save-devices-state` QMP command to get the QEMU save image. This is what libxl does and what happens implicitly when qemu-trad saves state. 
This patch adds this change and an extra debug line to track QMP messages sent to QEMU by xenopsd. This will add infrequent extra log lines, and most of these extra log lines are related to the QMP command Query_vnc, which we intend to remove soon anyway.
Tested successfully with vm.suspend/resume and vm.migrate.
Verified that the QMP.Stop command is being called as expected before QMP.Xen_save_devices_state:
```
Async.VM.suspend R:9feb1f745927|xenops] QMP.Command for domid 3: {"execute":"xen-set-global-dirty-log","arguments":{"enable":true}} …
```

CP-25316: Send QMP stop message before saving device state

---

xc/device.ml
xc/device.mli
xc/domain.ml
xc/domain.mli
xc/xenops_server_xen.ml

The function is_upstream_qemu is a somewhat fragile mechanism to select the
qemu profile from a domid because it uses a xenstore key that can be
manipulated by other processes outside xenopsd or race with threads inside
xenopsd. Manipulation of this key will lead to xenopsd selecting different
qemu profiles for the same domid, which can cause errors. An example of an
error caused by is_upstream_qemu is when Vm.shutdown is explicitly called on
a domid with a qemu-upstream profile. Vm.shutdown will eventually call Dm.stop,
which deletes this key. This races with the xenopsd xenstore watcher thread,
which can detect that the domid changed state to shutdown and then call
Dm.stop again via VM_check_state, causing the second Dm.stop that is executed
to run with the wrong qemu-trad profile …

CP-24831: improve selection of the runtime qemu backend in xenopsd

---

xc/xenops_server_xen.ml

During the execution of a VM_migrate operation, xenopsd transmits the VM
metadata using the function `Remote.VM.import_metadata`, which is executed on
the destination host. This function will eventually call `set_internal_state`
on the destination host, which recomputes some fields the VMExtra metadata for
the VM about to be received as a result of the migration, before persisting it
in the destination host.
This patch recomputes the profile field in VMExtra as well before persisting
this metadata, which is necessary to guarantee that the received metadata will
contain a profile consistent with the destination host. This is specially
significant if the destination host is a newer version of xenopsd, which could
associate different qemu backend profiles for the received VM metadata.
An …

cp-24831: persist qemu backend profile when importing VM metadata in migration

---

xc/device.ml
xc/device.mli
xc/domain.ml

qemu-upstream only terminates at the end of the suspend process, when the VM_destroy_device_model is called, producing the following xenopsd activity trace during suspend: VM_save -> Qmp.Xen_save_devices_state -> tap-ctl_close -> tap-ctl_detach -> VM_shutdown -> VM_destroy_device_model -> qemu_terminate -> tap-ctl_detach (again).
The problem in the trace above is that the tap operations occur before VM_destroy_device_model is called to terminate qemu-upstream, so tapdisk can't close the fds of the VBDs. This requires a workaround in the qemu-upstream patchqueue to close the fds of the VBDs when Qmp.Xen_save_devices_state is called. 
To remove the necessity of this workaround, the changes in this PR terminate qemu-upstream just after its state has been saved during the suspend operation …

CP-25156: change the suspend sequence in xenopsd for qemu-upstream

---

scripts/qemu-wrapper
xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

instead of using a network connection. This makes it easier to separate qemu-upstream in its own network namespace. A nice side-effect is that xenopsd knows the Unix path of the socket that was used when starting the qemu-upstream process and therefore QMP queries to qemu-upstream are not necessary anymore, simplifying the qemu-upstream backend.                                           
qemu-trad and PV VMs are not affected and continue to use a network connection for the VNC console.                                                                                           
This change depends on replacing the parameter for the VNC console from a network port to a Unix socket path when starting qemu-upstream, using the same matching vnc_socket_path used to connect to the console.
After …

CP-25570: connect to VNC console in qemu-upstream VMs using a Unix socket

---

xc/domain.ml

This was done in 0d1ce3b9 but partly lost when merging vgpu-migration.

CA-269046: Add "console/limit" again

---

scripts/qemu-wrapper

Change the arguments for starting GVT-g as required by corresponding
changes in qemu.pg.

CA-271407: qemu-wrapper: Change arguments for starting GVT-g

---

xc/domain.ml

When upgrading from XS6.2, a conversion function needs to be used to
convert the VM save stream to the new format.
- Originally, the conversion function would send a pipe fd to xenguest.
- After the introduction of the emu-manager code, a copy-paste error
prevented the pipe from being passed to emu-manager (which will pass
it along to xenguest), causing a VM migration from XS 6.2 to fail.
This patch fixes the issue by reusing the proper pipe fd to connect the
conversion function to emu-manager. It does so by replacing main_fd in
the call to with_emu_manager for pipe_r. It's not necessary to modify
vgpu_fd in this case because XS 6.2 will never have vgpu_fds.

CA-265581: pass pipe_r to emu_manager, as is done in xenguest helper

---

scripts/qemu-wrapper

Commit 34d357ac25b5 ("qemu-wrapper: Call unshare() before executing
QEMU") broke emulated NIC devices because the tap devices get opened in
a separate network namespace. Create the tap devices before starting
QEMU and pass them as open file descriptors. Implement it as a quick
workaround in qemu-wrapper for now to unblock the build, but this should
eventually be implemented somewhere else.

CP-25873: qemu-wrapper: Create tap devices before starting QEMU

---

xc/domain.ml

This was erroneously switched to Emu_manager. Note that this did not mean that
emu-manager was actually used, because the path to xenguest was still passed as
an argument to the connect function. But the log lines that are printed are
confusing.

Use XenguestHelper module for building domains

---

c_stubs/jbuild

See following diff:
```
$ diff xapi-xenopsd.install.orig xapi-xenopsd.install
3a4,12
>   "_build/install/default/lib/xapi-xenopsd/c_stubs/statdev.cmi" {"c_stubs/statdev.cmi"}
>   "_build/install/default/lib/xapi-xenopsd/c_stubs/statdev.cmx" {"c_stubs/statdev.cmx"}
>   "_build/install/default/lib/xapi-xenopsd/c_stubs/statdev.cmt" {"c_stubs/statdev.cmt"}
>   "_build/install/default/lib/xapi-xenopsd/c_stubs/statdev.ml" {"c_stubs/statdev.ml"}
>   "_build/install/default/lib/xapi-xenopsd/c_stubs/c_stubs.cma" {"c_stubs/c_stubs.cma"}
>   "_build/install/default/lib/xapi-xenopsd/c_stubs/libc_stubs_stubs.a" {"c_stubs/libc_stubs_stubs.a"}
>   "_build/install/default/lib/xapi-xenopsd/c_stubs/c_stubs.cmxa" {"c_stubs/c_stubs.cmxa"}
>   "_build/install/default/lib/xapi-xenopsd/c_stubs/c_stubs.a" …
```

Include the c_stubs in the xapi-xenopsd installation.

---

xc/domain.ml

This moves the code around to make sure that the event syncronization calls are always triggered, even in presence of errors, to prevent thread leaks.
Warning: this has not yet been tested, but I would welcome any preliminary feedback

CA-270640: Avoid leaking threads on error

---

lib/xenops_server.ml

The vgpu-migration protocol had to be changed to prevent a race condition,
causing vgpu-migration from pre-Jura to Jura hosts to block forever. The
only way to recover is to restart xenopsd. 
This patch interrupts the vgpu-migration if it detects the vgpu-migration
operation between these invalid hosts, preventing the block from occurring.
The vgpu-migration is interrupted before the VM state is saved -- therefore,
the VM in the sending host continues to run unaffected.
It works for vgpu-migration during both RPU and cross-pool migration.
The interruption occurs by xenopsd raising an Internal_error exception at
the receive_vgpu thread and sending a Handshake.error back to the main
migration thread of the sending host, which will clean up the main migration
threads in both the sender and …

CP-26145: cancel vgpu-migration between incompatible hosts

---

lib/xenops_server.ml

This patch series fixes two issues:
1) in case the VM_receive_memory thread raises an exception either in the VM_create or VM_restore operations, it should still kill the corresponding receive_vgpu thread.
2) there's a race in which the VM_receive_memory thread does not wait for the vgpu_receiver_sync table to be initialised in the receive_vgpu thread counterpart, also in the receiving host. The signal from the receiving host's receive_vgpu thread that the vgpu_receiver_sync table is already initialised reaches the sending host via the 'Synchronisation point 1-vgpu', but there's no signal from the sending host to the receiving host's VM_receive_memory thread. We add this missing signal from the sending host to the receiving host's VM_receivie_memory thread and call it 'Synchronisation …

CA-273775: Fix race in VM_receive_memory, and improve error handling

---

scripts/qemu-wrapper

While using jemalloc for QEMU decreases its memory usage, using it for
xs-clipboardd increases its memory usage (by 428 KiB RSS on average in
my test). Revert back to the default glibc allocator.

CA-265699: Don't use jemalloc for xs-clipboardd

---

scripts/qemu-wrapper

Tweak the jemalloc configuration to reduce QEMU's memory usage:
* narenas: jemalloc normally creates several arenas. Instead, create
only one.
* tcache: Disable the thread-specific cache of objects.
* lg_dirty_mult: Make jemalloc more willing to purge dirty unused
pages.
Testing showed that these changes reduced QEMU's memory usage by
900 KiB. While these changes are likely to reduce allocation performance
somewhat, we don't use QEMU for anything performance sensitive.

CA-265699: Tweak jemalloc config to reduce QEMU memory usage

---

scripts/qemu-wrapper

During a migration, QEMU is given a writable file descriptor to write
its save image. This could allow a denial of service since a rogue QEMU
could fill up the filesystem backing the file descriptor. To prevent
this, set the hard and soft limits of RLIMIT_FSIZE to 32 KiB. This is
enough for QEMU to save its migration state. QEMU is still free to write
to its emulated disks since this limit does not apply to block devices.

CP-26862: Set RLIMIT_FSIZE for QEMU

---

xc/device.ml
xc/device_common.ml
xc/device_common.mli
xc/domain.ml

This path "/local/domain//xenserver/attr" is created for guest
agent to report IP addresses on non-PV driver backed network device.
This change makes the guest agent has permission to read and write under
this path.
Signed-off-by: Ming Lu ming.lu@citrix.com

CP-26859: Update guest permission on "*/xenserver/attr" path

---

scripts/qemu-wrapper
xc/device.ml
xc/xenops_server_xen.ml

Reverts xapi-project/xenopsd#447

Revert "CP-24770: Xenopsd calls now the qemu-wrapper script passing in the right parameters for disks and CD drives."

---

xc/device.ml
xc/device.mli
xc/device_common.ml
xc/domain.ml
xc/xenops_server_xen.ml

There are 3 commits in this PR:
1. Revert to use Device.Generic.add_device on network SR-IOV
2. Add logic to cleanup xenstore paths of net-sriov-vf
3. Add device_kind_of function in module VIF
Signed-off-by: Ming Lu <ming.lu@citrix.com>

CP-26858: Update the xenstore path usage of network SR-IOV

---

xc/xenops_server_xen.ml

This prevents any of the components in suspending, for whatever reason, overwriting an earlier part of the suspend stream.  This can occur due to file pointer race conditions, and is causing issue.

CA-283704: The suspend stream should be opened with O_APPEND

---

xc/device.ml
xc/device_common.ml
xc/device_common.mli

This commit addresses several shortcomings of xenopsd/qmp interaction:
- no uniform model of sending QMP commends and checking for errors
- a mix of low- and high-level interaction
- no pairing of commands and results
This commit provides:
- A new function `qmp_send_cmd` to send commands to Qmp. The function
waits for the result of the command and checks it for success. In the
case of an error, it raises an exception. The `qmp_send_cmd` can
optionally send a file descriptor along with a command, as it is
required for some commands.
- `qmd_send_cmd` is implemented internally by function
qmp_send_cmd_internal that tags each command with an ID that is used
to wait for the identically matched response. Other responses received
in the meantime are logged but discarded.
- Interaction is now …

CA-282008 refactor qmp interaction for robustness

---

c_stubs/jbuild
c_stubs/stub_tap_open.c

We need to open /dev/net/tun with specific ioctl calls. This could be
implemented by either using a library like
https://github.com/mirage/ocaml-tuntap
or we can implement the specific use case directly and avoid the new
dependency. This commit is a direct implementation of the required
functionality. It is accessible from OCaml as:
external _tap_open : string -> Unix.file_descr = "stub_tap_open"

CP-25898 add tap_open() primitive

---

xc/device.ml

The original idea of this patch was to prevent files /var/run/xen/vnc-* accumulating between host reboots (contents in /var/run are cleaned up between reboots).
While testing the initial commit, I noticed that also /var/run/xen/qemu-event-<domid> and /var/run/xen/qemu-libxl-<domid> were also accumulating, and added corresponding commits for them.
Tested while rebooting VMs and the host, and files are removed after being used. QMP events and commands seem to be working fine when paying with the VM and observing the logs.

CP-25681: Prevent leakage of QEMU runtime files

---

scripts/qemu-wrapper
xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

This is miscellanous options except the display options (that will be part 2). I thought I'd split it to make it easier to review. I'm attaching results from dev testing.
[after_changes.txt](https://github.com/xapi-project/xenopsd/files/1745021/after_changes.txt)
[before_changes.txt](https://github.com/xapi-project/xenopsd/files/1745022/before_changes.txt)

CP-24772 part1: Moved miscellaneous options from qemu-wrapper to xenopsd

---

xc/device.ml
xc/device.mli
xc/xc_resources.ml
xc/xenops_server_xen.ml

According to deprivileged qemu design for usb passthrough part:
1. before passing through USB device
a) if it's the first USB device to pass through,
1) bind mount /dev,/sys in chroot directory.
2) create and join cgroup devices:/qemu-<domid>.
3) blacklist all and add a minimal white list("c 1:3 r", allow read /dev/null) to cgroup allow list.
b) change uid, gid of the device file.
c) add device to cgroup allow list if no device of the same type is allowed.
then xenopsd/device should
d) call Device_add using QMP
2. after stopping passing through USB device or the VM is shut down,
the function vusb_unplug in xenopsd/device should
a) call Device_del using QMP
and then call a function vusb_cleanup in usb_reset.py to execute:
b) restore uid, gid of the device file.
c) remove device from cgroup …

CP-27212: Update toolstack part when calling usb_reset.py

---

scripts/qemu-wrapper

With the recent vCPU hotplug changes, QEMU now saves some vCPU state
which increases the save file size. With many vCPUs, the limit is
tripped and suspend/migration fails. Increase the limit to 256 KiB.
With the maximum number of vCPUs and emulated devices, the save file
size was ~70 KB so this should be more than enough while still
preventing the guest from using much disk space.

CA-285426: Increase qemu save file limit

---

xc/device.ml

The address in the qemu command line needs to be in hexadecimal
notation.

Use hex address in qemu command line for NICs

---

xc/device.ml

The last version of the upstream qemu design makes it clear that the profile
qemu-upstream-compat will be incompatible with the future qemu-upstream one.
Therefore, we should prevent users from incorrectly using the unimplemented
qemu-upstream profile as an alias for the qemu-upstream-compat profile, before
qemu-upstream-compat becomes a supported feature.

CP-27171: remove qemu-upstream profile as valid option in the xapi vm record

---

xc/device.ml
xc/device_common.ml
xc/device_common.mli
xc/xenops_server_xen.ml

Duplicate ID ehci error is raised when multiple usb devices are passed to one vm. USB controller should be plugged only once when more than one usb device use the same controller.
This PR depends on https://github.com/xapi-project/xenopsd/pull/463

CA-285507: MultipleUSBPassthrough xenopsd internal error: Device_common.QMP_Error

---

scripts/qemu-wrapper

Since xenopsd now opens the tap device file descriptors, they are
inherited by the clipboard daemon which prevents the tap devices from
being properly removed when the guest unplugs emulated NICs. This can
cause some weird networking issues.
Ideally, we would use Python 3's pass_fds subprocess option to only keep
the required fd open for the clipboard daemon, but since we're using
Python 2.7, this is not available. Instead, just make sure to close all
the tap fds before execing the clipboard daemon.

CA-285400: Ensure tap devices are not held open

---

scripts/qemu-wrapper
xc/device.ml

These commits add an `addr` parameter for some QEMU devices:
* VGA: addr=2
* cirrus-vga: addr=2
* xen-pvdevice: addr=4+(number of NICs)
Examples for relevant `QEMU` arguments before (top) and after applying
these commits. In the case of xen-pvdevice, the machine has 7 NICs
(7+4=11=0xb), 
```
cirrus-vga,vgamem_mb=4,rombar=1,romfile=,subvendor_id=0x5853,subsystem_id=0x0001
cirrus-vga,vgamem_mb=4,rombar=1,romfile=,subvendor_id=0x5853,subsystem_id=0x0001,addr=2
VGA,vgamem_mb=8,rombar=1,romfile=,subvendor_id=0x5853,subsystem_id=0x0001,qemu-extended-regs=false
VGA,vgamem_mb=8,rombar=1,romfile=,subvendor_id=0x5853,subsystem_id=0x0001,addr=2,qemu-extended-regs=false
xen-pvdevice,device-id=0xc000
xen-pvdevice,device-id=0xc000,addr=b
```

CA-285245 add addr parameters to QEMU command line

---

lib/xenops_utils.ml
xc/xenops_server_xen.ml

This passed a (smallish) stress test where VMs underwent many lifecycle operations.

CA-284768: Fix race between metadata DB updates

---

lib/xenops_utils.ml
xc/device.ml

This implements removing the /var/xen/qemu/root-<domid> directory hierarchy after QEMU finishes.
Cleanup code is now split:
* Dm_Common.stop
* Qemu_upstream_compat.Dm.stop - removes /var/xen/qemu/root-<domid>
* Qemu_trad.Dm.stop - removes /var/xen/qemu/<pid>
Unlike /var/xen/qemu/<pid>,  /var/xen/qemu/root-<domid> is not expected to be empty such that removal has to be recursive. New code for this resides in Xenops_utils.Unix.rm.
This has been tested with device models qemu-trad and qemu-upstream-compat.

CP-27114 cleanup /var/xen/qemu/root-<domid> for QEMU

---

xc/xenops_server_xen.ml

The issue to be fixed in this commit is that SR-IOV VF backed vif
didn't return the real Vif.active when the SR-IOV VF (PCI) is not
plugged. This makes XAPI think this VIF should be removed and set its
currently_attached as false in a rebooting scenario. Consequently, XAPI
would find the metadata of VM changed, and push new memtadata to
Xenopsd, during which XAPI filtered out the un-attached vifs in new
metadata. Finally, this vif would not be created in the guest.
The fix is to make VIF.get_state return real value of active, nomorally
it is true, so that XAPI will not set this vif as non-attached.
Signed-off-by: Ming Lu <ming.lu@citrix.com>

CA-285751: Fix VIF.get_state to return Vif.active as reality

---

scripts/qemu-wrapper
xc/device.ml

This PR removes the argument '-gfx_passthru' for all the qemu profiles (qemu-trad and QEMU upstream). The gfx_passthrough argument is unnecessary after the changes in CP-24243.
Tested with a Windows VM in qemu-trad and qemu-upstream-compat profiles. For both profiles, after attaching a GVT-d passthrough VGPU to the VM and starting the VM:
* the vgpu_pci key in the VM.other-config field was populated with the corresponding pci device as expected, and /usr/log/daemon.log showed that -gfx_passthrough is not used anymore. 
* the windows guest displayed a new display device, which was found by the corresponding Intel Iris Pro driver, and the windows rebooted in Aero mode and was able to provide the corresponding Windows Experience Index for the attached VGPU.
```
dom0# xe vm-list …
```

CP-27285: Implement GVT-d as normal passthrough

---

xc/device.ml

When calling usb_detach in usb_reset.py, we shouldn't reply on the
result of qom-list as when the vusb is successfully unpluged, the
qom-list will return nothing of the vusb, but we still need to do detach
work. So this is a wrong judgement.
This is somehow related to https://github.com/xapi-project/xen-api/pull/3517. 

CA-284857: call usb_reset_detach unconditionally

---

scripts/qemu-wrapper

This basically adapts the same code from qemu-dm-wrapper for qemu-trad.
QEMU builds e1000 as an alternative model that is sometimes used for
debugging (e.g. netsted virt) and testing.

Support toolstack override of NIC device model for debug purposes

---

xc/xenops_server_xen.ml

The xenstore watch @introduceDomain will be emitted whenever a new
domain turns up. We have a thread that reacts to this and installs watches
for the new domain if it's one xenopsd is interested in. The problem occurs
here because xenopsd decides whether a domain is interesting or not based on
whether it has metadata about the VM in its VmExtra database, `DB`. This
was only stored on completion of the VM_create call, which is after the
domain is created, and hence there was a race between the two threads. This
commit ensures there is an entry in the VmExtra database before the
domain is created, thus removing the race.

CA-286115: Remove race between DB and xenstore watch thread

---

xc/device.ml

As restore uid/gid of usb device file will be included in usb_reset script, so pass
uid/gid to usb_reset script is not needed anymore.
Another PR https://github.com/xapi-project/xen-api/pull/3525 is related with this.

CP-27216: no need to pass uid/gid

---

scripts/qemu-wrapper
xc/domain.ml
xc/domain.mli
xc/stubdom.ml
xc/xenops_server_xen.ml

xenguest now takes a -vgpu parameter when building a VM that has a nvidia vgpu.
For other (v)gpu vendors, including pass-through for any vendor, this parameter
is not sent to xenguest.

CP-27545: pass -vgpu argument from xenopsd to xenguest when using nvidia vgpus

---

xc/device.ml

We've found that things continue to work without these patches. I've tested VM export / import, xenmotion, suspend/resume, start/stop, and these all worked fine without these patches.
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

Revert changes to hotplug rules and direct-io-safe

---

scripts/qemu-wrapper

This complements the changes to xenguest and hvmloader which in complex
serves as additional protection from unpredictable MMIO hole size
fluctuations that might occur for a variety of reasons. Although,
it's expected that all migration streams starting from Kolkata
will have this key, we still need to guess the size of MMIO hole for
the VMs from the previous releases (Jura and older) and handle them as
default cases - hence there is still the special handling for legacy
and vGPU VMs.

CP-27581: Move MMIO hole size key to a persistent location

---

xc/xenops_server_xen.ml

The issue in CA-267368 is that 'timeoffset' of a HVM VM fails to be written to xenstore path "/local/domain/DOM-ID/platform/timeoffset" in a localhost migration.
The cause is Xenopsd stores 'timeoffset' into two places: persistent data and non_persistent data. While in a localhost migration, Xenopsd would not re-generate the non_persistent data since it has existed already. This makes 'timeoffset' data in non_persistent data out of sync with the one in persistent data.
Per @jonludlam and @mseri comments, actually root cause is Xenopsd "has a 'nonpersistent' state that's persisted."
Therefore, in these commits, each data in non_persistent data will be:
1. either removed if it will not be changed since creation. It can be re-generated once it is needed, or
2. moved into persistent data if …

CA-267368: Move/Remove non_persistent data

---

scripts/qemu-wrapper

QEMU's stdout and stderr are connected to a forkexecd child proccess
which is responsible for logging to syslog. This forkexecd child does
not remain running when using qemu-trad since it logs to syslog via its
privileged half. Since the forkexecd child is fairly heavyweight,
replace it with "logger" which does the same thing but uses
substantially less memory.
Unfortunately, to have the logs prefixed with QEMU's pid implies
starting QEMU before logger which requires a fair amount of code
refactoring in the wrapper so that QEMU is started as a subprocess and
logger is exec()ed rather than exec()ing QEMU directly.

CA-287928: Use logger for upstream QEMU logging

---

lib/xenops_utils.ml

In the old implementation of finally() (shown below), an exception
raised by g() in the with-block would escape:
```
let finally f g =
try
let result = f () in
g ();
result
with e ->
Backtrace.is_important e;
g ();
raise e
```
Whether this is the correct behaviour or not is debatable but it lost
the exception e, which was the primary failure. This commit changes the
behaviour to ignore exceptions raised by g() in the with-block and to
always re-raise e.
This problem was hit in CA-288207: during cleanup of a cancelled task,
g() in a finally block raised an exception that escaped and lost the
original exception. This does resolve the behaviour observed
(migration fails with internal error about contacting
QEMU) but it does not resolve it completely. In testing I have seen a
failure with …

CA-288207 fix finally()

---

xc/device.ml

QMP command Blockdev_change_medium implements CD changes. It now is more
explicit about the format of the CD and specifies "raw".
This depends on corresponding changes in qmp (part of xs-opam).

CA-287881 use "raw" format for Blockdev_change_medium

---

xc/domain.ml

Same as #509, but for 0.52-lcm.

CP-28088: Tell xenguest about GVT-g

---

xc/domain.ml
xc/domain.mli
xc/xenops_server_xen.ml

Emu-manager can use qmp to tell qemu to start dirty tracking - but this
feature must be enabled with the command line argument "-dm qemu".
This commit adds option -dm qemu to the invocation of Emu-Manager if the
domain is using upstream QEMU.

CP-23308 pass "-dm qemu" to emu-manager

---

xc/device.ml
xc/device.mli
xc/domain.ml

Once the emu-manager work is merged, the call to
xen-set-global-log-dirty in the toolstack is not needed anymore. This
commit removes it.

CP-24775 remove with_dirty_log() code and calls

---

scripts/qemu-wrapper

VMs with raw disks (i.e. using a RawHBA SR) have a backend of "vbd" in
xenstore rather than "vbd3". Search for this in xenstore as well
otherwise QEMU won't open them.

CA-289887: qemu-wrapper: Detect raw disks

---

lib/jbuild
lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_skeleton.ml
lib/xenops_utils.ml
xc/domain.ml
xc/domain.mli
xc/jbuild
xc/xenops_server_xen.ml

When we do a migrate we currently construct a new domain on the destination with the same uuid as the source. Doubly confusing when we do a localhost migrate.
This PR uses a temporary (but related) uuids during the migration. In fact, it goes a little further than just the domain and actually renames _all_ of the VM's metadata, so all tags on queues and database objects as well as domain uuid and xenstore trees reflect the temporary name. When the VM is paused on the source it is renamed there first, then the destination is renamed back to the original uuid.

Migrate with unique UUID

---

scripts/vif-real

If the VM does not have PV drivers installed, then the tap device
will not be removed.  This means the bridge drops it's MTU down to
the tap device's default MTU of 1500.
Signed-off-by: Bob Ball <bob.ball@citrix.com>

CA-292860: Ensure MTU is set for TAP devices

---

scripts/qemu-wrapper

Xen documents /local/domain/%d/image/device-model-pid as the xenstore
path for QEMU's pid and libxl relies on this path to correctly destroy a
domain. Set this path in qemu-wrapper which makes "xl destroy" work with
QEMU upstream VMs.  qemu-trad watches for @releaseDomain itself which is
why "xl destroy" works with qemu-trad VMs.

CA-292873: Allow "xl destroy" to work with QEMU upstream VMs

---

xc/device.ml

If the profile is unknown, use qemu-upstream-compat. In general,
qemu-trad should not be used but the fallback must remain as qemu-trad
at this point to avoid breaking PV guests. This was detected because
there was a typo in the Other Install Media template.

CA-292656: Use qemu-upstream-compat if profile is unknown

---

lib/storage.ml

Currently, attaching a VBD to a VDI on a GFS2 SR causing a storage backend error and accompanying backtrace.
Unfortunately, while Xapi-storage-script reports this backtraces in JSON format, Xenopsd expects an S-expression. This causes an S-expression parsing failure, obfuscating the actual error and making debugging very difficult.
This commit patches Xenopsd's backtrace handling to expect a backtrace in JSON, and should enable easier debugging of the VDI attach error.
Signed-off-by: Akanksha Mathur <akanksha.mathur@citrix.com>

CA-287333: Xenopsd should report storage backtraces in JSON, not as an S-expression

---

scripts/qemu-wrapper
xc/device.ml
xc/xenops_server_xen.ml

This patch rebases commit ffddbbfb414d7a83ecde14f07fa0809941af5c9c                                                                                           
> CP-24770: Xenopsd calls now the qemu-wrapper script passing in the right                                                                                           
> parameters for disks and CD drives.                                                                                           
> Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>  
In particular, it simplifies the change to the VmExtra.qemu_vbds field after                                                                                           
the VmExtra.non_persistent_t field was removed and qemu_vbds is available …

CP-24770: create QEMU disk command line in xenopsd instead of qemu-wrapper

---

dbgring/jbuild

This adds the dbgring tool to the xapi-xenopsd-xc package such that it
gets built.

Build dbgring tool by default

---

xc/device.ml

Currently, only the cdrom with the userdevice index 3 can be used,
because the QMP cdrom used is just the static QEMU device "ide1-cd1".
This patch finds the QEMU device dynamically from the cdrom backend device,
so that a cdrom with any userdevice index can be used.
Tested by starting a VM with a cdrom with different userdevice indexes:
device ( RO): xvda
userdevice ( RW): 0
xenopsd-xc: [debug||14 |Async.VBD.insert R:320a814efd63|xenops] QMP command for domid 11: {"execute":"blockdev-change-medium","id":"qmp-000002-11","arguments":{"device":"ide0-cd0","filename":"/dev/fdset/0","format":"raw"}}
device ( RO): xvdc
userdevice ( RW): 2
xenopsd-xc: [debug||43 |Async.VBD.insert R:b91f84a29dea|xenops] QMP command for domid 12: {"execute":"blockdev-change-medium","id":"qmp-000006-12","arguments": …

CA-292693: use the corresponding QMP device of a cdrom userdevice

---

scripts/qemu-wrapper

hvm_serial is often used for Windows kernel debugging and it typically
requires that QEMU uses the network (either actively making a connection
or passively waiting for a connection). If hvm_serial is set, don't
unshare the network namespace otherwise the common debugging use case is
broken.
This is not a security risk since preventing QEMU from using the network
is a defense-in-depth and hvm_serial should only be used for debugging.

CA-291050: qemu: Don't unshare network namespace when hvm_serial is set

---

scripts/vif-real

If the VM does not have PV drivers installed, then the tap device
will not be removed.  This means the bridge drops it's MTU down to
the tap device's default MTU of 1500.
Signed-off-by: Bob Ball <bob.ball@citrix.com>

CA-294081: Backport CA-292860: Ensure MTU is set for TAP devices

---

xc/emu_manager.ml

CA-290688 don't kill emu-manager on cancel
This changes what happens when a migration is cancelled:
* previously, emu-manager was killed by a signal
* now, we send the "abort" command instead
In both cases the connection to emu-manager is closed afterwards.
This was tested with BVT, BST. It depends on a corresponding change in emu-manager.

CA-290688 send "abort" on cancel to emu-manager

---

lib/suspend_image.ml
xc/domain.ml

emu-manager waits until process_header is finished, and the resume
thread in xenopsd is waiting first for emu-manager to finish, and then
for the process_header threads.
If process_headers raises an exception the resume deadlocks.
The cancel callback on the task already has the right logic to send an
abort command to emu-manager, so call that as soon as we know we got an
error.
We need to do this before we attempt to Event.sync, because that would
deadlock as the other thread is xenopsd is not waiting for a reply from
this thread yet (it is waiting for emu-manager to finish first).
Tested this by raising an exception on purpose and xenopsd correctly canceled the resume task, and put the VM back into suspended state (so I could retry the resume):
```
Aug  2 12:25:49 xrtuk-07-02d …
```

CA-295092: cancel resume task if process_header raises an exception

---

xc/domain.ml

xenopsd was failing with a 'no such file or directory' in Bios mode.

UEFI: fix VM suspend in Bios mode

---

xc/jbuild

Also link only against ppx_sexp_conv.runtime-lib
This may be related to https://discuss.ocaml.org/t/reducing-mirageos-image-size-using-ocamlclean/2481

jbuild: remove ppx_deriving_rpc from libraries

---

lib/jbuild

The full ppx rewriter should not be linked in the library. Apologies, I missed it earlier

lib/jbuild: link only ppx_sexp_conv.runtime-lib

---

xc/device.ml

When starting DEMU, we are expecting it to report a "good" state. This
adds "resuming" as a good state and avoids a race where we have missed
the two earlier states "initialising" and "running".

CA-296924 add "resuming" as a good DEMU state

---

scripts/block
xc/device.ml

To increase performance, OVMF can use PV drivers. A previous change to
XAPI (9d0eb8f80507, CA-50383) prevented the VBD backend from being
created for HVM CD-ROMs due to some interaction with blkback.  However,
blktap3 is now used as the backend for CDs and there doesn't seem to be
any issue with it. Therefore, remove the code which prevents creating
the physical-device node to allow OVMF to use PV drivers.

CA-297602: Always create a physical-device node for HVM CD-ROMs

---

xc/domain.ml

We're currently reverting the corresponding xenguest change 2a09b3c1e272
(CA-289607: xenguest: Include GVT-g device in MMIO hole calculation).
Treating GVT-g as passthrough device was technically incorrect initially
and the problem itself was present due to the other reasons.
(See CA-293487).
This reverts commit 49ec3aa8cbf7c86e941d623b8dd4be9fe082327c.

Revert "CP-28088: Tell xenguest about GVT-g"

---

xc/device.ml

Xenopsd monitors the QMP connection to QEMU in a thread and executes QMP
commands in it. In case the QMP connection closes (for any reason) it
simply removes the corresponding domid but does not escalate this. This
commit makes Monitor.add more robust by making it raising an exception
if communication fails. This is only effective when Monitor.add is
called from outside the thread from init_daemon - as it happens in
CA-298525. Any exceptions inside the thread is logged but ignored
otherwise.
Trying to start a VM when the issue occurs leads now to the following
error:
An emulator required to run this VM failed to start
vm: e0267811-4386-7fb4-ad1b-6dc8dd685b1e (Windows 8.1)
name: domid 10
msg: QMP failure at File "xc/device.ml", line 2247, characters 59-66
Signed-off-by: Christian Lindig …

CA-298525 make QMP interaction more robust

---

xc/xenops_server_xen.ml

if exception occured in function with_reservation, the reservation request send to squeezed before
will leaves all the lifetime of the host, and other vm will not allocate because squeezed will record
it as reserved.

Fix reservation left when exception occur in with_reservation

---

Makefile
scripts/send_message.py
xc/jbuild
xc/xc_resources.ml
xc/xenops_server_xen.ml

1. Add a new thread to watch xen event
2. Call xapi to send message when receive ENOMEM event from xen
3. Introduce a script to call xapi to send message. (This script is necessary
because xenopsd cannot call xapi-client directly due to the dependency limitation.)

CP-28951: Call xapi to send message when receive xen lowmem event

---

xc/device.ml

Changes to arguments passed to varstored.

CP-29100: Remove PCI Device and expose IO port for communication with varstored.

---

xc/xenops_server_xen.ml

This call causes problems on Xen 4.11. Also, it turned out that it did not
actually do anything at all.
In the medium term, we want to go back to handling PCI passthrough entirely in
xenopsd, without calling out to `xl`.
This has been tested on both old and new Xen.

CA-254698: Drop call to `xl pci-detach` on PCI.unplug

---

scripts/qemu-wrapper
xc/device.ml
xc/device.mli

This is intended for UEFI boot.
The commit lacks a ticket number, and actually making UEFI default to this, I just opened the PR for some discussion.
At @pauldu request I've limited the number of emulated disks to 1, and lowered the number of emulated NICs.
We should probably refactor the assignment of devices to have less hardcoded numbers, and have an actual list of devices and addresses so that xenopsd knows how to pick the next "free" one. [This](https://github.com/xapi-project/xenopsd/blob/master/xc/device.ml#L2571-L2576) would break if we ever want to support more than one vGPU for example.

CP-29857: Use NVME when platform:device-model=qemu-upstream

---

scripts/igmp_query_injector.py

After upgrading Dom0 to CentOS7.5, scapy upgrade from v2.3.0 to v2.4.0 and IGMP
class has been refactored, so we have to change the code to adapt the changes.

CA-301452: adapt new version scapy igmp changes

---

xc/xenops_server_xen.ml

The following commits for Xen 4.8 changed cpuid featuresets a bit:
https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=20e92c97f904aa460e2223c30dcad36c234496b6
https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=38b1c3a5affbe3451f366576aef9c7149d62de04
This prevents VM migration from 4.7 to 4.8+ versions of Xen. The new
featuresets are more architecturally correct, but are not compatible
with the old ones from Xapi POV.
Fake up those feature bits for Xapi. It's safe to do and will be replaced
by the new CPUID/MSR policy work in the future.
Signed-off-by: Sergey Dyasli <sergey.dyasli@citrix.com>

CA-254835: make Xen 4.8+ featuresets compatible with Xen 4.7

---

lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_skeleton.ml
xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

NVME devices are not yet migratable by QEMU, and we can't recover from VM.save errors from QEMU currently (we don't support fast resume).
Instead there is a new QMP command that we can use to check whether QEMU considers the domain migratable (based on its devices), if they are not we should forced migration and suspen in xenopsd
(the migration would be rejected or crash if we attempted to do it).
Introduce a new assert_can_save API, and update the nomigrate flag whenever we receive events from the VM (e.g. because it unplugged its NVME device switching to PV drivers and becomes migratable).
I'd like to have a discussion whether updating the nomigrate flag is the right thing to do here, or if we should instead add another method in xcp-idl xenops_interface to query the migratable state. …

CP-29936: UEFI: block migration when NVME devices are present

---

lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_simulator.ml
lib/xenops_server_skeleton.ml
scripts/common.py
xc/domain.ml
xc/domain.mli
xc/stubdom.ml
xc/xenops_server_xen.ml

The step of VM rename in migration will break the network connection of the target VM in DVSC scenario. This Pull request aims to fix that.

CA-303253: XenMotion breaks VIF connectivity when using DVSC

---

xc/device.ml

Reverts xapi-project/xenopsd#582
This seems to cause an 0x80042256 error during windows install in the bvt. Revert it until we understand why

Revert "CA-299737: set cache=none for disk devices"

---

scripts/qemu-wrapper
xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

In UEFI boot mode we get a chance to start fresh with a new version of
QEMU device-model, so move all the code that is needed for backwards compatibility
into the qemu-upstream-compat profile.
Testing on Ring3 BST indicates the new device models work fairly well, the most risky change here is changing the machine type.

CP-29827: drop some trad-compat options

---

lib/jbuild
lib/xenops_sandbox.ml
lib/xenops_utils.ml
xc/device.ml

This would cause some confusing log messages at best, or even fail in the worst case (if varstored-guard is not running). So just avoid doing it if we are not using UEFI mode.

CA-302981, CP-30032: Do not try to stop/destroy varstored chroot in BIOS mode, and sandbox varstore-rm

---

xc/domain.ml

Remove code that waits for a domain to disappear. The code can only
observe whether a domain disappears as expected but not to anything if
it doesn't. This however, can also be observed from the outside so there
isn't really a good reason to keep this code around.
This is a backport of 4e375dd6 from the master branch.

XSI-103 CA-298916 don't wait for domain to disappear

---

xc/device.ml

To allow merging qemu and toolstack components independently,
we should be backwards compatible with older versions of qemu
that do not support this command.
The 'query-migratable' command is useful for detecting problems that
would prevent migration early (e.g. NVME device attached),
but is not relevant for BIOS boot mode.

CA-305090: do not fail on older versions of qemu

---

xc/device.ml

It is not obvious for xenopsd when the QMP socket is ready. So far we
only wait for the path to appear but this does not mean it is ready
and trying to connect to it can still fail. Now we are also trying to
establish a connection before returning. If connecting fails, we wait
and try again until the timeout is reached.

CA-304519 wait for QMP socket by connecting to it

---

xc/device.ml

These got introduced with the varstored changes, but this message gets
logged way too often, and distracts from finding real errors.

xenopsd: silence failed to read PID messages

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

Note: this is currently on top of the uefi branch, once that is merged this can be retargeted to master.
This build has passed a BVT, waiting on a BST now.
Opened this for discussion on whether this is the right approach.
Things to be careful of when dropping qemu-trad: PV guests defaulted to qemu-trad and called some functions from there (even though qemu is usually not running when PV guests are used, unless you enable some experimental flags to get the PV framebuffer). These functions were no-op on qemu-trad (qemu was not running), but they failed on qemu-upstream (it tried to send QMP commands).
Therefore I introduced a new qemu-none profile for PV guests that do not fail if qemu is not present (and indeed would refuse to start qemu), and dropped support for the experimental PV …

CA-305139, CA-293696, CP-24362, CP-25605: drop qemu-trad 

---

xc/device.ml

This is no longer required for GVT-g.

CP-29962: Stop passing -vgt_monitor_config_file argument to QEMU

---

xc/device.ml

We need to do this, because this is what qemu-trad used to do, and we need to
provide the same virtual hardware to VMs that are migrated from previous
releases using qemu-trad.

CA-309144: use xen platform rev 1 if no device-id specified

---

xc/device.ml

In the case of QMP negotiation failure, remove() is called but it does
not know the connection that it needs to close. This commit makes sure
remove() does know it by adding the connection to the lookup table
before calling Qmp_protocol.negotiate() (which might fail and trigger
the cleanup case).

CA-309685 fix fd leak in QMP connection handling

---

scripts/block
xc/device.ml

Still testing, but it looks like reverting this change makes CDROM unplug run more reliably in the pool stress test.
On master we get `Watch.Timeout 300` on VBD unplug of a CDROM: the hotplug-status key does not get removed and tapdisk is throwing errors when told to remove the device. Looks like a race condition.
When reverting the change as this PR does don't see timeouts anymore.
Not sure whether there are better solutions than reverting this patch, it looks like the no-physical-device was there to workaround a kernel bug initially, and that bug is still present with blktap3 and tapdisk?
@rosslagerwall any suggestions?

CA-306943: Revert "CA-297602: Always create a physical-device node for HVM CD-ROMs"

---

xc/domain.ml

Creation of a domain includes creating its XenStore hierarchy. This
includes empty device entries for VIFs and VBDs as they are required for
Windows - see commit e894ebfd4cbe039adccf8ba78f4912ed373cc95d.
This commit introduces a check to not create them to work around
a bug in a VM that would trip over these empty directories. Since
Windows guests depend on the empty entries, this should almost never be
used. Empty directories are not created when the platform contains this
key:value: netscaler:XSI-254.

XSI-254 don't create empty /domain/N/device/vif

---

xc/domain.ml

Creation of a domain includes creating its XenStore hierarchy. This
includes empty device entries for VIFs and VBDs as they are required for
Windows - see commit e894ebfd4cbe039adccf8ba78f4912ed373cc95d.
This commit introduces a check to not create them to work around
a bug in a VM that would trip over these empty directories. Since
Windows guests depend on the empty entries, this should almost never be
used. Empty directories are not created when the platform contains this
key:value: netscaler:XSI-254.
Backport of edd538a604ecc8752d659a6cf16ba9056160cbc5. Changes only in
whitespace because the 0.17-lcm branch uses tabs at the beginning of the line.

XSI-254 don't create empty /domain/N/device/vif [backport]

---

xc/xenops_server_xen.ml

Commit 8c07000b3b1c ("CA-254835: make Xen 4.8+ featuresets compatible
with Xen 4.7") missed one more feature bit that was removed in Xen 4.9:
https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=c783556d71084c8111ce17304992c2e85f0e0346
This prevents VM migration from 4.7 to 4.9+ versions of Xen on AMD cpus.
Fix this by using a similar workaround until new CPUID/MSR levelling
is implemented.
Signed-off-by: Sergey Dyasli <sergey.dyasli@citrix.com>

CA-308199: fix VM migration to Xen 4.9+ on AMD machines

---

xapi-xenopsd.opam

They are no longer available anywhere and it breaks the build:
https://github.com/xapi-project/xs-opam/pull/352
Example of broken build: https://travis-ci.com/psafont/xen-api/jobs/187564273#L1781

maintenance: do not apply patch for building

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

Tested for cross-pool migrations from Lima to master, for VMs that were started with qemu-trad as well as qemu-upstream-compat. I have verified that the revision field was set as "expected" and the migration passed.

CA-313709: Fix migrations from older versions for VMs without device_id

---

scripts/qemu-wrapper

Most of xl utilities while quering for domain type are trying to
distinguish between HVM and PVH by reading /libxl/<domid>/type key.
It now mostly works because the default behavior is to assume the
domain is HVM and show a warning.
Set the key explicitly to "HVM" to avoid the warning and confusion.

CA-314511: Set "type" key for HVM domains that is expected by xl

---

scripts/xen-backend.rules.in
xc/device.ml
xc/hotplug.ml

xenopsd was unplugging the VBD too soon for qemu-dp backends (SMAPIv3/GFS2), while the guest was still using it, even if the guest set the error field in xenopsd saying 'Device in use'.
On a clean shutdown of a device we can only unplug it once both the frontend and backend have reached state Closed (6), otherwise the PV ring can become corrupt because the frontend/backend will be confused about the device's state (xenopsd deletes the xenstore key, so the state would be unknown).
See commit messages for more details. This passed the original test that found CA-314170 (it now claims 'Device in use' and refuses to unplug), which revealed a bug in the testcase, and it also passes the fixed testcase. The GFS2 functional suite also passed.
The problem with my previous pull request was that it …

CA-314170: fix vbd unplug for qdisk backends

---

scripts/block
xc/device.ml

https://github.com/xapi-project/blktap/commit/a7832564b4d7e540d2d5a85e2556f571b7f9d89b has fixed the bug in blktap that required reverting this change, so we can now put this change back in.
This is required for UEFI booted guests to be able to use PV drivers in the firmware, which is required if you want to have multiple USB boot devices (as required by SVVP tests).
We were not able to reproduce the original failure in XenRT after the blktap fix.

CA-309841: allow using PV drivers for CDROMs again

---

lib/xenops_hooks.ml
lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_simulator.ml
lib/xenops_server_skeleton.ml
xc/xenops_server_xen.ml

Because of the current dance of uuids during migration some scripts get confused and need the domids to properly work.

CA-314715: Pass domid argument to hooked scripts

---

lib/xenops_server.ml
lib/xenops_server_plugin.ml
xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

Change the type of VGPU_start atomic to support multiple vGPUs in resuming.

CP-31060: Support multiple vGPUs in resuming.

---

xc/device.ml

What's inside the PR:
- Handle the whole list of vGPU. In prior we handle the head only.
- Make parameters to DEMU (new "--device" format).

CP-31060: Support multiple NVIDIA vGPUs in VM startup.

---

xc/device.ml

See https://github.com/xapi-project/forkexecd/pull/38 for background.
Best reviewed commit by commit, ignoring whitespace. First I try to simplify and refactor existing code and then I switch varstored to use systemd.
Tested on a box and was able to successfully start/stop/suspend/resume/reboot a VM with the transient unit (varstored-4) showing up and then disappearing.
XenRT tests pending.

CP-30037: use systemd to spawn varstored (reduce memory usage)

---

xc/domain.ml

Change the order of FLR and de-assigning. Previously we did de-assigning
before resetting a device, then if the device had a ongoing DMA, the
device may cause the memory corrumption when it was back to Dom0.
Resetting a device will notify the device to stop DMA.
Backport of dededb3c97b50d4164bc5596c11462445fe44fa6

Backport FLR fix

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

From XSI-353, since the upgrade to QEMU upstream the ability to access
the serial console of an HVM guest using xl console or xenconsole has
been broken.
This commit adds code to query QEMU for the path of the serial device
and writing it to xenstore:
/local/domain/<domid>/serial/0/tty <ptypath>

CA-318579 write serial device to xenstore for HVM

---

xc/device.ml

Signed-off-by: Lin Liu <lin.liu@citrix.com>
As titled, add support for extra_args for vgpu.
Customer can set extra args for the vgpu by command 
```xe vgpu-param-set uuid=xxxx extra_args="key1=v1,key2=v2"```
This is very similer to the previous verion of 
``` xe vm-param-set uuid=xxx platform:vgpu_extra_args="key1=v1,key2=v2"```

CP-31321: Support extra_args for vGPU configuration

---

lib/xenops_server.ml

The fault was caused by wrong handling of VGPU_start operation when migrating a VM without any vGPU.
VGPU_start shouldn't be triggered then.

CA-314693: Live migration failure without any vGPU.

---

xc/device.ml

The new code in xenopsd only supports HVM guests.
It is unclear whether anyone would still be using PCI passthrough to PV guests, we haven't explicitly documented that it is not supported, so add it back and fall back to the old code for it.

CA-320215: use xl pci attach for PV guests

---

lib/xenops_server.ml

Currently, xenopsd assume only one vGPU exist in VM during migration, otherwise an error will be reported.
This PR release the restraint.

CP-31545: REQ-720, Support live migration of VM with multiple vGPUs.

---

xc/device.ml

For compatibility with old tools and Naples.
device-id is still 2 in the template (and in xenstore) for UEFI,
but not in qemu, which confuses things.
The template can be updated to remove the device-id in the future,
however it cannot be done yet because the old tools fail with device-id
1.

CA-320361: use device-id if it exists

---

lib/xenopsd.ml
xc/device.ml

The NVidia vGPU metadata that comes from older xenopsds contains a config_file
path rather than a type_id and VGPU UUID. Match config_file and type_id up in
the lookup file that xapi has helpfully created to handle this case. The VGPU
UUID is not available at all, but we just use the all-zero UUID. XAPI uses the
UUID to distinguish between multiple VGPUs on a VM. However, there is only one
VGPU per VM in this upgrade case, so the UUID is not really required.

CA-321983: Handle vGPU migration from older releases

---

xc/domain.ml

xenguest "-vgpu" argument is added for single vGPU, it should also be
added for multiple vGPUs case. This fixs system hang with 4 vGPUs.
Signed-off-by: Talons Lee <xin.li@citrix.com>

CA-320189: miss "-vgpu" argument for multiple vGPUs

---

xc/device.ml

This replaces "or" by (||) to avoid a compiler warning.

Use (||) not "or", avoid warning

---

lib/ionice.ml
xc/xenops_server_xen.ml

1. Fix parsing output from ionice(1) by recognising scheduling classes
"none" and "unknown". There is no clear description in the ionice
manual page what these mean but they are emitted by ionice
nonetheless. This commit commit accepts these but returns None.
2. Don't call ionice when the result isn't used.

CA-322786 improve ionice handling

---

lib/xenopsd.ml
xc/device.ml

Delete nvidia_compat_lookup_file as now demu keep backward compatibility
Signed-off-by: Lin Liu <lin.liu@citrix.com>

CA-322749: Make toolstack work with old Nvidia host drivers

---

xc/device_common.ml

This does not move the chroot path, because this might contain core dumps
that could be large.
It also does not move the demu save path, since GPU data can be very large.
The qemu restore record is limited to 1MiB in xenopsd.
A stress test and Ring3 BST has passed.

CA-233384: move qemu save/restore to tmpfs in /var/run

---

lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_simulator.ml
lib/xenops_server_skeleton.ml
xc/xenops_server_xen.ml

The `simplified` parameter of xenopsd backends was invented specifically for
the xenlight backend. When a backend was `simplified`, this meant that certain
sub-operations could be skipped. E.g. a `VM_start` did not need to include
device plug sub-operations, because these were implicitly done by the
`VM_build` sub-operation.
Now that the xenlight backend has been removed, all the remaining backends are
non-simplified, so we can remove this concept and associated code altogether.
This patch takes the opportunity to make the `atomics_of_operation` function a
little easier to read (hopefully), and removes an out-of-date comment about
QEMU.

Simplify by removing simplify

---

lib/storage.ml
xc/xenops_server_xen.ml

We now honour the existing API of Datapath.attach by
passing the domid of vm that the vbd is being attached to.
This will enable a qemu process per vm.
Signed-off-by: ben sims <ben.sims@citrix.com>

CP-31450: Add domid to Datapath.attach

---

xc/device.ml

In rare cases, an exception raised from this function during a VM reboot can
cause a call to `VM.stat` to fail. If this happens, then xapi may conclude that
the VM is halted, while it is actually rebooting. This is a problem, because
the VM will be marked as halted rather than running after the reboot.
There is a mechanism in xenopsd that always marks a VM as running, in replies
to `VM.stat`, while it is being rebooted, even when the VM is actually down at
the time. In this case it did not, due to the exception, and xapi concluded "VM
state missing" and reset the power-state.

CA-323893: Catch exceptions in Device.PV_Vnc.is_cmdline_valid

---

lib/dune
test/dune
xc/dune

It can be added again once dune properly supports bisect_ppx.

maintenance: remove bisect_ppx preprocessing

---

xc/domain.ml

The fork flag is ignored by xenguest and hence does not have to be
passed.

CA-325129 don't pass -fork true to xenguest

---

xc/domain.ml

This patch unconditionally enables IOMMU mappings to stop pass-through
test cases from being broken. A better soltion is needed before release,
creating mappings for only those guests to which hardware is assigned.
Signed-off-by: Paul Durrant <paul.durrant@citrix.com>

CP-31782 update domain create interface

---

xc/xenops_server_xen.ml

Currently shim_mem argument of pv-shim is being calculated automatically
by PVinPVH_memory_model_data.shim_mib. Since (1) the formula used there
can go out-of-date with the Xen version of pv-shim and (2) to allow
a user a fine-grained control of amount of pv-shim memory, introduce
a new shim_mib (Int64) parameter in vm.Vm.platformdata.
Signed-off-by: Sergey Dyasli <sergey.dyasli@citrix.com>

CP-32111: Make shim_mem configurable

---

lib/xenops_server.ml
lib/xenops_utils.ml

Xapi sends a VGPU map to update PCI addresses during migration. This
commit adds code to update an optional virtual PCI function (VF) that
was introduced for SR-IOV support. This commit depends on a
corresponding commit in Xapi but maintains backwards compatibility.

REQ-627 CA-325131 update VGPU VF mapping

---

lib/xenops_server.ml

The previous commit was using the wrong function to look up all VGPus of a VM. This one fixes it.

fixup! REQ-627 CP-31787 disable shared EPT for nvidia SRIOV

---

lib/xenopsd.ml
xc/domain.ml

Apparently, old Linux HVM guests still require this workaround to be
present on upgrade from previous releases if it was originally applied
there.
This reverts commit 64f98d0c575f70ba170a393cd0d59fae417f6a31.

CA-327280: Revert "Remove workaround for CA-140252"

---

xc/xenops_server_xen.ml

Video memory in not needed in PVH mode because there is no qemu
to emulate VGA. Having video_mib also gets in the way of calculating
PVinPVH memory: build_max_mib ends up less than static_max_mib
plus shim_mib (see memory/memory.ml in xcp-idl).
Signed-off-by: Sergey Dyasli <sergey.dyasli@citrix.com>

CA-325848: PVinPVH: set video_mib to 0

---

lib/xenops_server.ml

For NVidia SRIOV vGPUs the PCI plug operation needs to happen before
QEMU is started. This is possible because these PCI devices are not
advertised to QEMU via QMP and thus don't require QEMU to be running.
This commit splits the list of PCI devices into early (before QEMU) and
(after QEMU) plugs and builds the PCI_plug operation accordingly. The
PCI_plug operation takes a new flag "qmp_add_devive" which indicates
whether the PCI device is advertised to QEMU. Obviously the flag needs
to be false for devices plugged early and true for those plugged late.
This does not create a problem for migration from older releases
because those don't have SRIOV vGPUs and all PCI devices are plugged
late and in the same order as before.

REQ-627 CP-322210 split PCI_plug ops into early/late

---

lib/xenops_server.ml

This fixes an earlier oversight: for `VM_start`, we need to plug SRIOV PCI devices before creating the device model. Otherwise we would miss them,

fixup! REQ-627 CP-322210 split PCI_plug ops into early/late

---

lib/xenops_server.ml
xc/domain.ml
xc/xenops_server_xen.ml

Migration of a VM without VIFs got stuck at:
```
Caught Xs_protocol.Enoent("directory"): cleaning up VM stat
```
Some more debugging showed it failed when trying to move this xenstore
entry, which was missing:
```
/xapi/8e8c58cd-eba4-cde3-e1e5-000000000001
```
The intention of this code seems to have been to ignore missing entries,
so do that by ignoring Enoent on the root of a tree.
Do not ignore Enoent on entries deep in the tree since that would
indicate a race condition elsewhere.
With these changes I was able to successfully complete a localhost migration of a VM without a VIF, which was failing previously.
Signed-off-by: Edwin Török <edvin.torok@citrix.com>

CA-327906: don't fail migration if a xenstore directory is missing

---

lib/xenopsd.ml
xc/device.ml
xc/device.mli
xc/xenctrlext.ml
xc/xenctrlext.mli
xc/xenctrlext_stubs.c
xc/xenops_server_xen.ml

This commit makes changes for CA-297891, in which a special domain is
used in Xen to quarantine the PCI devices for pass-through. The
quarantine means a separate I/O address space for DMA of PCI device. Two
cases are considered in this commit:
1. when a PCI device is going to be passed-through to a guest domain, it
will be placed into quarantine firstly (done by toolstack). Later on,
when it is deassigned from the guest domain, it will be placed (done by
Xen) to quarantine domain, rather than the dom0.
2. when a PCI device, which had been passed-through to a guest domain and
now it is in quarantine, is going to be managed by host driver running on
dom0 to emulate virtual devices (not PCI pass-through), it should be
moved out from quarantine and assigned back to dom0. I.E. NVIDIA vGPUs
and …

CP-31431: Add quarantine/dequarantine for PCI devices

---

lib/xenops_server.ml
xc/device.ml
xc/device.mli
xc/domain.ml
xc/xenops_server_xen.ml

* Backport for CA-327906 "don't fail migration if a xenstore directory is missing" from 
8c3756b9.
* Revert of "CA-318579 write serial device to xenstore for HVM". This was reverted because it was never released and requires support in OCaml QMP which makes it difficult to build.

Backport of CA-327906 - don't fail migration if a xenstore directory is missing

---

c_stubs/xenctrlext_stubs.c

The latest Ubuntu 19.10 only has Xen 4.9 headers, so is missing the new
cpuid and msr policy functions, which causes Travis CI and local builds
outside of a container to fail.
Add back the compatibility definitions so that the CI and local builds
work (where we only need linking to succeed and unit tests to run).
We didn't notice the CI error before, because the PR that introduced this change required changes in xcp-idl too, and the CI is expected to fail in such cases (it can't deal with multiple PRs spread across repos).

Fix CI: add definitions from new xenctrl.h

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

Previously a floppy VBD would be treated as a
disk, which caused xenopsd to filter out that vbd
when deciding what args to execute qemu with.
Signed-off-by: lippirk <ben.anson@citrix.com>

CA-330162 Ensure floppy options are passed to qemu

---

xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

This is a backport of CA-330162 to 8.1.
Needs to go in alongside https://github.com/xapi-project/xen-api/pull/4002

Allow guests to see floppies

---

lib/xenopsd.ml

We need to always have PV-shim output in our system logs to assist
analysis of potential failures in the field. This still leaves
an option to override console settings using "pvinpvh-xen-cmdline"
since only the last value will take effect.

Always add "console=xen" prefix to PV-shim cmdline

---

xc/device.ml

Module Pervasives is deprecated, use Stdlib instead.

Use Stdlib.compare instead of Pervasives.compare

---

lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_simulator.ml
lib/xenops_server_skeleton.ml
xc/device.ml
xc/device.mli
xc/xenops_server_xen.ml

The commits in this PR introduce:
* an API call to de-quarantine a PCI device
* a PCI_dequarantine operation used during VM start
The API call is required because Xapi needs to configure drivers of PCI devices (just like xenopsd) and for this a PCI device must be de-quarantined. 
This PR depends on corresponding changes in xcp-idl: https://github.com/xapi-project/xcp-idl/pull/302 which has been reverted but needs to be active for this PR to work. Travis is broken because of the cross-repo dependencies.

REQ-627 CA-333495 Introduce PCI.dequarantine

---

lib/xenops_server.ml

During migration we perform a handshake operation. If it fails, we try
to recover the error by trying to parse the error message as JSON.
However, the message could be something else which leads the JSON parser
to fail. We need to capture this exception in order to generate a proper
error message.

CA-335206 catch exception from Rpcmarshal.unmarshal

---

xc/xenops_server_xen.ml

The latter is an alias of the former in ocaml-xen-lowlevel-libs, and only
makes the code harder to follow.
Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>

Use get_cpu_featureset instead of get_featureset

---

cli/main.ml
cli/xn.ml
dbgring/dbgring.ml
dbgring/dune
doc/walk-throughs/VM.start.md
lib/bootloader.ml
lib/cancellable_subprocess.ml
lib/dune
lib/suspend_image.ml
lib/tuntap.ml
lib/xenops_server.ml
lib/xenops_server_simulator.ml
lib/xenops_utils.ml
lib/xenopsd.ml
list_domains/list_domains.ml
suspend_image_viewer/suspend_image_viewer.ml
test/test.ml
xc/cancel_utils.ml
xc/device.ml
xc/device_common.ml
xc/domain.ml
xc/dune
xc/emu_manager.ml
xc/hotplug.ml
xc/list_domains.ml
xc/stats.ml
xc/xenguestHelper.ml
xc/xenops_helpers.ml
xc/xenops_server_xen.ml
xc/xenops_xc_main.ml

Because Stdext is not used directly, Monadic and Opt modules are not imported at all and Std is not imported for xapi-xenopsd.
The latest commit builds xenopsd cleanly in a xenserver mock chroot.

Cleanups around Stdext: Stop using Opt and Stdext directly

---

.travis.yml
lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_skeleton.ml
xc/xenops_server_xen.ml

This allows other daemons to hide the temporary uuid from their clients
by reading the value from xenstore.
Since rename is both used on the origin and destination of the
migration and both need different operations on xenstore, a parameter
was added to differentiate between the stages.

CA-335964: store the original vm uuid when starting migration

---

c_stubs/xenctrlext_stubs.c
lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_simulator.ml
lib/xenops_server_skeleton.ml
xc/domain.ml
xc/domain.mli
xc/xenctrlext.ml
xc/xenctrlext.mli
xc/xenops_server_xen.ml

Shutdown code 5 means that a domain has kdump kernel loaded and is ready
for a jump to it. This is possible if either the domain is crashed
and we need to load a crash kernel or kexec has been called as part of
e.g. a fast reboot. Code 5 needs to be handled by calling a special
operation called "soft reset" for the domain. This will ensure the domain
is ready for the next enlightned Linux kernel to go through its boot
sequence. The side effect of this operation means xenstore and console
event channels are closed for guest domain and need to be recreated.
The rest of the domain state stays untouched meaning kdump boot process
will follow the same path as bugcheck kernel of Windows guests.
For now only support 1 soft reset per domain lifecycle which corresponds to
crash dump usecase. To …

CP-28375: Implement soft reset handler for guest kdump support

---

xapi-xenopsd-cli.opam

See that xapi-xenopsd-cli.opam was added in https://github.com/xapi-project/xenopsd/pull/692/files, but the url still pointed to xenops-cli.git
xenops-cli was moved to xenopsd as xapi-xenopsd-cli,
but this opam file was not updated.

maintenance: point xapi-xenopsd-cli.opam to correct repo

---

lib/xenops_server.ml

Suppose we are migrating a VM from src -> dest. If dest's xenopsd fails
after having copied the memory across, the src xenopsd will hang until
you restart the toolstack. After restarting, you are left unable to perform
power operations on the VM using the xen api.
This PR improves the situation by:
- causing such a migration to fail promptly rather than hanging
- after toolstack restarts, you can turn the VM off with a force shutdown; 
thereafter, you can shutdown / reboot / start as usual
This PR _doesn't_ get the metadata completely right unfortunately. The toolstacks
don't correctly reflect the VM's `resident_on` metadata after the failed migration.
The correct value is assumed after restarting toolstacks, but subsequently force shutting
down the VM causes the pool to think that the VM …

Improvements to a class of migration failures

---

xapi-xenopsd-simulator.opam

Update opam metadata to reflect the removal of the tests.
This will be followed by an update on xs-opam to pick up the change.

opam: simulator does not run tests (nor ounit) anymore

---

lib/suspend_image.ml
lib/xenops_server.ml
lib/xenops_server_simulator.ml
test/test.ml

Testing suggests this introduced a regression in a rolling pool upgrade.
This reverts commit 5176b5b372fb2a67be9d5477d80d6080abbe52b8, reversing
changes made to aa8a311ee120238d11a078d59db2c7e1488d1219.

CA-347611: Revert CA-332779 (a fix for XSI-555)

---

xc/domain.ml

To help with debugging EINVAL access seen in xenstore logs, log such
occurrences even when we expect and ignore them.

Log when we receive EINVAL from xenstore

---

.ocamlformat
lib/suspend_image.ml
lib/suspend_image.mli
lib/xenops_server.ml
test/test.ml
xc/domain.ml
xc/xenops_server_xen.ml

- add unit test from the xenopsd Stockholm branch
- replace some usages of ``[`Ok of 'a | `Error of 'b]`` with `('a, b') Result.t`

maintenance: formatting + port sexp test + use Result.t rather than custom type

---

c_stubs/xenctrlext_stubs.c
lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_simulator.ml
lib/xenops_server_skeleton.ml
xc/domain.ml
xc/domain.mli
xc/xenctrlext.ml
xc/xenctrlext.mli
xc/xenops_server_xen.ml

This PR is intended to contain kdump exclusively changes (these changes are in 0.150-lcm already: #745). It is intended that the branch 0.150.2-lcm will be tagged as 0.150.2.1, giving us:
0.150.2 (base) < 0.150.2.1 (kdump only) < 0.150.5 (kdump + other stockholm fixes)

UPD-738 port kdump on top of 0.150.2

---

lib/xenops_server.ml

In case of a localhost migration, we already have the VM metadata, but
we still export+import to remap VDIs and VIFs. These functions must
now be called directly, because the VM.import_metadata API queues the
operation and blocks (this is not the same on newer branches, where
separate, temporary UUIDs are used for the source and target).

CA-352061: Call VM.import_metadata directly during localhost migration

---

lib/xenops_utils.ml
lib/xenopsd.ml
xc/xenops_server_xen.ml

Introduce a byte based quota 'vm-guest-agent-xenstore-quota-bytes'.
Deprecate 'vm-guest-agent-xenstore-quota' (and convert it to bytes based
on worst case size estimates).
On startup create a table with how many bytes each character can take up
in the various JSON/XML encodings that we use, and use that to calculate
quota usage.
The default is set to the byte equivalent of the previous 128 quota, but
avoids issues where a lot of small xenstore keys/values hit the 128
quota (e.g IP addresses in OpenStack).
Signed-off-by: Edwin Török <edvin.torok@citrix.com>

CA-351685: improved fix for XSA-354

---

lib/xenops_utils.ml
lib/xenopsd.ml
xc/xenops_server_xen.ml

Backport of https://github.com/xapi-project/xenopsd/pull/739
Note: this will need .spec file dependencies to ensure that we have the new message-switch from https://github.com/xapi-project/message-switch/pull/60 too!

Improved fix for XSA-354: backport

---

lib/xenops_server.ml

If we call additional functions between `with e` and `raise e`, these may raise and catch internal exceptions of their own which would overwrite our stacktrace.
Make sure to save the stacktrace first thing in the exception handler, which marking it as important does.
One such example of lost stacktrace is a Not_found exception from Stringext.split which is caught internally (and probably caught by a Uri marshaling function?)

Do not lose stacktraces when handling exception in VM.receive_memory

---

lib/xenops_server.ml
suspend_image_viewer/suspend_image_viewer.ml

These were unused opens and an incomplete match to a record
suspend_image_viewer was not being built and the commit fixes
compilation errors

maintenance: avoid warnings, fix suspend_image_viewer

---

lib/xenops_utils.ml
lib/xenopsd.ml
xc/xenops_server_xen.ml

Stockholm and Yangtze have diverged in xenopsd.git. This is the yangtze equivalent of what we have already done for Stockholm:  https://github.com/xapi-project/xenopsd/pull/764
CA-351685 also requires a change to message-switch, but there we'll have yangtze share the stockholm tag/branch for now

[yangtze] backport CA-351685

---

.github/workflows/0.150-lcm.yml
.github/workflows/0.150.5-lcm.yml
.github/workflows/main.yml

The current scheduled action failed because it was not updated to last week's changed branches.
Update falti/dotenv-action to the latest version, it only changes it's dependencies' versions.

ci: fix 0.150.0 for yangtze and add 0.150.5 for stockholm

---

lib/xenops_server.ml
xc/xenops_xc_main.ml

This is another piece of logic that was blocking vbds being plugged into dom0
I need to run a final BST to ensure no regressions, hence the no merge flag.

CA-334758 - Allow plug of vbds for sds vms

---

configure

Use TMPDIR instead if it's provided

configure: work around read-only /tmp found in opam's 2.1.0

---

cli/xn.ml
configure
lib/xenopsd.ml
xc/device.ml
xc/dune

I had to do an additional change regarding the usage of the epoll bindings because they were moved in Core 0.14.0, this was not needed on master because these were replaced by polly.
I've also added the workaround for opam 2.1.0 to be able to compile it locally with opam

CP-38064: adapt code to ppxlib 0.9

---

squeezed/lib/squeeze.ml
squeezed/src/squeeze_xen.ml
squeezed/src/squeezed.ml
squeezed/test/dune
squeezed/test/squeeze_test.ml

Xcp_service used to be able to configure where squeezed logged to but it doesn't seem to work anymore.
Set the facility to local5 which logs to xensource.log
I've taken the liberty to change the tests to alcotest to avoid using the same (flawed) logging facilities for the testing code and the tested code.

CA-357785: squeezed logs to xensource.log

---

lib/task_server.ml
lib/xenops_server.ml
lib/xenops_utils.ml
xc/xenops_xc_main.ml

To debug a potential memory leak, not intended for merging yet.

CP-38343: backport xenopsd memory usage tracking to Havana

---

lib/xenops_server.ml

There are certain tasks that are run asynchronously without anyone
waiting for the result (e.g. import_metadata_async).
Allow setting a flag on these tasks, so that they are cleaned up when
finished (either successfully or not).
Needed to avoid space leaks due to an ever growing tasks/updates list.
Signed-off-by: Edwin Török edvin.torok@citrix.com

CA-361220: xenopsd: introduce TASK.destroy_on_finish

---

lib/xenops_sandbox.ml
xc/device.ml

For debugging lost FDs in varstore-guard, log when whe call it to stop
serving a domain. Backport from xen-api.git
* 53d0f47642207d9fdf3ae2a08c19de17d57bf47f

CA-364138 log when about to stop varstored and varstore-guard

---

test/dune
xapi-xenopsd-cli.opam

Otherwise the CI tries to run them as part of xapi-xenopsd-cli and will
fail to find a library

test: run as part of the xapi-xenopsd package

---

lib/xenops_server.ml

Backport of def684e1873bb0829dd679887900f3b3e6d559b6 from xen-api.git
There may be a problem with some VMs, but we must always let xenopsd start.

CA-369444: Ensure xenopsd still starts if VM state upgrade fails

---

lib/dune
lib/open_uri_https.ml
lib/xcp_client_https.ml
lib/xenops_server.ml

This is a backport of several commits; we omit those that in the original code deal with certificate checking as this is not present in this code base.
The original code is in xen-api.git but in the backport is split into xe-api.git, xenopsd.git, and xen-api-libs-transitional.git.
Socket keepalives do not work when stunnel is used, as the given fd is the local connection to stunnel, and are not set in HTTPS mode. This is fine, because the stunnel client is already set up with keepalives.

CP-41796 Close Port 80 (Encrypt Data Transfer During VM Migrations)

---

cpuid/cpuid.ml
cpuid/cpuid.mli
cpuid/dune
lib/xenops_server.ml
lib/xenops_server_plugin.ml
lib/xenops_server_skeleton.ml
test/dune
test/test.ml
test/test_cpuid.ml
test/test_cpuid.mli
xc/dune
xc/xenops_server_xen.ml

Backport of https://github.com/xapi-project/xen-api/pull/5076.
Depends on:
* https://github.com/xapi-project/xen-api/pull/5091
* https://github.com/xapi-project/xcp-idl/pull/336

CP-43468: push CPUID logic down from xapi into xenopsd

---

scripts/qemu-wrapper

QEMU has a file size limit to prevent denial of service attacks. However with the introduction of vTPM the vTPM state is now saved in the qemu device stream. If the vTPM happens to have a lot of data then the quota is hit, qemu returns an error, the migration fails and XAPI kills the original VM.
(Same bug happens if we were trying to take a checkpoint, the VM ends up dead).
Fixing that would require fast resume, which we don't have, however the file size limit needs to be updated. Don't try to be too tight on the size, the vTPM may be a max of 256KiB, so increasing this to 512KiB should work, but to be safe double that to 1MiB.

CA-381503: bump qemu filesize limit (Backport)

---

.github/workflows/0.150-lcm.yml
Makefile
lib/bootloader.ml
lib/bootloader.mli
lib/open_uri_https.ml
lib/resources.ml
lib/xcp_client_https.ml
scripts/make-custom-xenopsd.conf
scripts/pygrub-wrapper
xapi-xenopsd.opam
xc/xenops_server_xen.ml

Instruct pygrub to drop its privileges
This comes from the hotfix released yesterday

CA-383491: Invoke pygrub in depriv mode
