xc/device.ml, xc/device.mli, xc/xenops_server_xen.ml, xl/xenops_server_xenlight.ml
Original pull request: https://github.com/xapi-project/xenopsd/pull/159
This updated PR fixes a build failure.
Requires https://github.com/xapi-project/xcp-idl/pull/47
=> [RFC] xc: support floppy disk images (take #2)

libvirt/xenops_server_libvirt.ml, qemu/xenops_server_qemu.ml, xc/xenops_server_xen.ml, xl/xenops_server_xenlight.ml
Note, this depends on xapi-project/xcp-idl#49.
=> Forward port read caching API

xl/xenops_server_xenlight.ml
Add in o_direct_reason into xl/
=> Attempt to fix the build

.travis.yml, lib/xenops_server.ml, lib/xenopsd.ml
Signed-off-by: David Scott <dave.scott@citrix.com>
=> Update to cohttp.0.15.2

xc/xenops_server_xen.ml, xl/xenops_server_xenlight.ml
Add device in guest_agent for xapi to handle.
Signed-off-by: Hui Zhang <hui.zhang@citrix.com>
=> CP-10531: Add device in guest_agent.

libvirt/xenops_server_libvirt.ml
Signed-off-by: David Scott <dave.scott@citrix.com>
=> Fix the libvirt backend build

xc/xenops_server_xen.ml
Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>
=> [CA-155888] remove reservation id after domain build completes

xc/xc_path.ml
Signed-off-by: Jon Ludlam <jonathan.ludlam@eu.citrix.com>
=> Change alternatives path: s/xcp/xapi/

scripts/vif-real
=> XOP-627: Failure to add a vif to a bridge is a hard error

lib/xenops_server.ml, lib/xenops_server_plugin.ml, lib/xenops_server_skeleton.ml, simulator/xenops_server_simulator.ml, xc/xenops_server_xen.ml
Depends on xapi-project/xcp-idl#95
=> CAR-1744: add support for running in-guest user scripts

lib/xenops_server.ml, lib/xenops_server_plugin.ml, lib/xenops_server_skeleton.ml, xc/xenops_server_xen.ml
Signed-off-by: Euan Harris <euan.harris@citrix.com>
=> CP-14811: Add function to upgrade old-style VM feature sets

xc/xenops_server_xen.ml, xc/xenstore_watch.ml
Signed-off-by: Koushik Chakravarty <koushik.chakravarty@citrix.com>
=> CA-186732: Add domain id as token during xs.watch

lib/xenops_server.ml
Signed-off-by: Koushik Chakravarty <koushik.chakravarty@citrix.com>
=> CA-179027: Handle vm_receive_memory failure in xenopsd

test/test.ml, xc/domain.ml, xc/domain.mli, xc/stubdom.ml, xc/xenops_server_xen.ml, xl/xenops_server_xenlight.ml
Change
auto_update_drivers to has_vendor_device and
auto-update-drivers to has-vendor-device everywhere.
=> CP-14832: rename auto_update_drivers to has_vendor_device

xc/xenops_server_xen.ml
=> CA-190329: Add watch on attr Xenstore key

xc/xenops_server_xen.ml, xc/xenstore_watch.ml
Signed-off-by: Koushik Chakravarty <koushik.chakravarty@citrix.com>
=> CA-191570: Make use of meaningful tokens during xenstore watch

lib/xenops_server.ml
This reverts commit 427fd97.
We cannot remove the VM from Xenospd from within Xenopsd during a failed
VM_receive_memory because during localhost migration we need the
metadata to be there for the cleanup operations of the sender to
succeed.
=> CA-198209: Don't remove metadata during failed VM_receive_memory

lib/xenops_server.ml
We do not want to use = when comparing queues: queues can contain
(uncomparable) functions, and we are only interested in comparing
the equality of their static references.
=> CA-184556: do not use = when comparing queues

lib/xenops_server.ml
for each of its default and parallel queues.
=> CA-201166: Redirector must hold a different mutex n

lib/xenops_server.ml, lib/xenops_server_plugin.ml, lib/xenops_server_skeleton.ml, simulator/xenops_server_simulator.ml, xc/device.ml, xc/device.mli, xc/device_common.ml, xc/device_common.mli, xc/hotplug.ml, xc/xenops_server_xen.ml, xl/device_common.ml, xl/device_common.mli, xl/xenops_server_xenlight.ml
Implement VIF.set_ip{v4,v6}_configuration and related.
Signed-off-by: Chunjie Zhu <chunjie.zhu@citrix.com>
=> CP-15358: Support external IP address setting in VMs

lib/xenops_hooks.ml, lib/xenops_server.ml
Signed-off-by: Rob Dobson <rob.dobson@citrix.com>
=> CP-15613: Add an additional hook for VM pre-suspend.

scripts/setup-pvs-proxy-rules
=> setup-pvs-proxy-rules: announce we are done only at the end

lib/bootloader.ml
=> CA-220466: Guest reads/deletes in dom0 via grub config

lib/xenops_server.ml, lib/xenopsd.ml
CP-20600: vGPU migration: set up connection for data
Just the first step of implementing this: not handling the data
itself yet, and we still need to make streams go in parallel.
=> CP-20600: vGPU migration: set up connection for data

xc/cancel_utils.ml, xc/device.ml, xc/domain.ml
Some things I noticed on when reading some xenopsd code.
=> Random minor improvements

lib/xenops_server.ml
We do this by adding them all to the same worker queue.
=> CP-21636: Serialise all operations on MxGPU VMs

configure.ml
Ported from https://github.com/xapi-project/ocaml-xen-lowlevel-libs/pull/100
=> configure.ml: More robust way to detect whether xentoollog needs linking

scripts/vif-real
=> CP-22269: Remove multicast toggle on VIF

xc/domain.ml, xc/xenops_server_xen.ml
=> UPD-64: backport fixes for CA-227101 and CA-248130

.travis.yml
Signed-off-by: Frederico Mazzone <frederico.mazzone@citrix.com>
=> Update Travis: Build against Falcon RPMs

lib/xenops_server.ml, lib/xenops_utils.ml, xc/device.ml, xc/xenops_server_xen.ml
Depends on https://github.com/xapi-project/xcp-idl/pull/157.
=> Vgpu mapping for migration

_oasis, xc/device.ml
=> CP-18194: Use QMP to change CD media (insert/remove)

xc/device.ml, xc/device_common.ml, xc/device_common.mli
=> CP-17622: Use QMP to get the QEMU save image

lib/xenops_utils.ml
If two threads are simultaneously trying to remove "foo/bar1" and "foo/bar2"
from the FileFS module, each thread will try to remove ["foo/bar{1,2}"; "foo"],
deciding whether it's a directory or file by `stat`ing them. There was logic
to catch the ENOTEMPTY when the first one tries to rm foo, but if both threads
remove their "bar"s before either tries to remove the "foo", the first will
rm "foo" successfully but the second would get an error trying to stat the
file. This c/s fixes that exception.
=> CA-258444: Fix a race when removing files from the filesystem

scripts/qemu-dm-wrapper
@andyhhp : Please review the patch. I have addressed your comments.
=> introduce nic_type as a configuration option .

xc/xenops_server_xen.ml, xl/xenops_server_xenlight.cppo.ml
=> Use ppx version of memory-interface rpcs

xc/device.ml, xc/device_common.ml, xc/device_common.mli
=> CP-21131: Get VNC port using QMP

xc/xenops_server_xen.ml
=> refine the indent

README.md
Signed-off-by: Frederico Mazzone <frederico.mazzone@citrix.com>
=> Add README badges: Build Status and Lines of Code

xc/xenctrlext.ml, xc/xenctrlext.mli, xc/xenctrlext_stubs.c, xc/xenops_server_xen.ml
=> CP-23797: Call new domctl during vCPU hotplug

xc/device.ml
When a new connection is added to the QMP event thread, it writes a byte
to a pipe to wake up the event thread to add the new fd, but this byte
is never consumed so epoll_wait() will subsequently always return
immediately because the pipe is ready to read. Furthermore, when the
pipe is added to the monitor, wakeup() is called which immediately
triggers this loop. This causes xenopsd-xc to consume 100% of a CPU.
Fix this by removing the pipe entirely since it is not needed according
to the epoll_wait man page:
"While one thread is blocked in a call to epoll_pwait(), it is
possible for another thread to add a file descriptor to the
waited-upon epoll instance. If the new file descriptor becomes ready,
it will cause the epoll_wait() call to unblock.
Signed-off-by: Ross Lagerwall …
=> CA-266874: Fix infinite epoll wakeup loop

.travis-python-nosetests.sh, .travis.yml, Makefile, lib/xenopsd.ml, scripts/igmp_query_injector.py, scripts/test_igmp_query_injector.py, scripts/vif-real, xc/xc_resources.ml, xc/xenops_server_xen.ml
=> REQ-230 merge feature branch to master

lib/xenops_server.ml, xc/xenops_server_xen.ml
=> VUSB.unplug: ignore exception when domain does not exist

Makefile, configure.ml, scripts/make-custom-xenopsd.conf, scripts/qemu-wrapper
Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>
=> CP-25344: Moved the qemu-wrapper script in to the xenopsd repo.

scripts/qemu-wrapper
To be done in xenopsd properly with CP-25150 and CP-25572.
=> Add some security options to qemu-wrapper

xc/device.ml
As QEMU will soon be running inside a chroot, it will be unable to save
its device state correctly when given a filename. Instead, open the file
inside xenopsd and pass it a file descriptor instead (this is similar to
how the CD is changed).
=> CP-25317: Give QEMU an open fd for saving the device state

simulator/jbuild, suspend_image_viewer/jbuild
=> jbuild: fix xenopsd dependency name

scripts/block
Signed-off-by: Jonathan Davies <jonathan.davies@citrix.com>
=> scripts/block: fix incorrect variable name

lib/xenops_server.ml
Previously, the code looked something like this:
```ocaml
let rec perform op =
let one =
match op with
| Vm_shutdown -> do_shutdown ()
| Check_state ->
if needs_shutdown then perform Vm_shutdown
in
try
one op
with e ->
(* trigger cleanup actions *)
match op with
| Check_state -> () (* if checking state, no cleanup required *)
| Vm_shutdown -> perform Check_state
```
the idea was that we didn't need to do any cleanup operations if Check_state
failed. However, what was happening was that the call to `perform` in the
body of Check_state entered another exception handler that thought the
operation being performed was `Vm_shutdown`, and thus a failure there would
cause _another_ call to `perform Check_state`
The new code separates `perform` into two functions, one with no exception
handler …
=> CA-254911: Don't trigger cleanup actions when triggering cleanup actions

lib/jbuild
=> xenopsd: add missing dependency

lib/platform.ml, xc/domain.ml, xl/xenops_server_xenlight.cppo.ml
Signed-off-by: Akanksha Mathur <akanksha.mathur@citrix.com>
=> Use String.lowercase_ascii over deprecated String.lowercase

lib/tuntap.mli
=> CP-25898 fix syntax error

xc/device.ml
This is for adapt sriov idl changes.
=> Adapt sriov idl changes

scripts/xen-backend.rules.in, xapi-xenopsd-xc.opam, xc/device.ml, xc/device_common.ml, xc/hotplug.ml, xc/jbuild, xc/xenops_server_xen.ml, xl/device_common.ml
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>
=> Merge of qemu-datapath into REQ477/master branch

xc/device.ml
This commit changes how the address of the xen-pvdevice is calculated:
* If there is no vGPU device, the address is 2
* If there is no xen-platform-device, the address is 3
* Otherwise, it is the smallest unused address >= 4
The slots >=4 are used by NICS. So we scan the NICs and find the first
gap in the list of addresses being used.
=> CA-286261 calculate address of xen-pvdevice

xc/device.ml, xc/device.mli, xc/device_common.ml, xc/device_common.mli, xc/domain.ml, xc/hotplug.ml, xc/jbuild, xc/xenops_server_xen.ml, xl/xenops_server_xenlight.cppo.ml
Merge feature SR-IOV to master
BST passed in job 81743
BVT passed in job 81742
=> Merge feature SR-IOV to master

xc/device.ml
This reverts commit cb59fd758715c2e7867a35df359187714cfc45de.
=> Revert "Set direct-io-safe=1 to allow direct i/o"

xc/device.ml
Previously, if during QEMU startup we timed out waiting for the QMP
socket to appear, we would miss closing open file descriptors passed to
QEMU because wait_event_socket() would raise an exception. This commit
protects against this with a finally() wrapper.
=> CA-288350 don't leak fd if QEMU startup too slow

scripts/qemu-wrapper
=> CP-27696: Additionally pass QEMU arguments into the upgrade script

xc/xenops_server_xen.ml
Signed-off-by: Akanksha Mathur <akanksha.mathur@citrix.com>
=> CP-26583: Upgrade Xenopsd to use PPX-based idl of Rrdd

.travis-python-nosetests.sh
=> travis-python-nosetests: fix tests

lib/cancellable_subprocess.ml, lib/io.ml, lib/suspend_image.ml, lib/suspend_image.mli, lib/xenops_migrate.ml, lib/xenops_utils.ml, xc/device.ml, xc/domain.ml, xc/readln.ml, xc/xenops_server_xen.ml, xl/xenlight_events.ml, xl/xenops_server_xenlight.cppo.ml
This needs to be reviewed very carefully
=> xenopsd: make safe-string compliant

lib/io.ml
=> CA-289145: Close socket if error occurs when connecting

lib/xenopsd.ml, xapi-xenopsd-xc.opam, xapi-xenopsd.opam, xc/device_common.ml, xc/emu_manager.ml, xc/xenguestHelper.ml
This depends on xs-opam 4.1.0 being released
=> update interface to fd-send-recv >= 2.0.0 

xc/domain.ml
Otherwise, device with ongoing DMA may cause Dom0's memory corruption.
Signed-off-by: Wei Xie <wei.xie@citrix.com>
=> CA-289561: Do FLR before deassigning device.

lib/storage.ml, scripts/qemu-wrapper, xc/device.ml, xc/device_common.ml, xc/device_common.mli, xc/xenops_server_xen.ml, xl/xenops_server_xenlight.cppo.ml
This has been reviewed previously and had a nightly test run.
Has to be merged together with:
https://github.com/xapi-project/xcp-idl/pull/232
https://github.com/xapi-project/xapi-storage-script/pull/73
https://github.com/xapi-project/xapi-storage/pull/89
https://github.com/xapi-project/xen-api/pull/3645
https://github.com/xapi-project/xenopsd/pull/524
<specfile change>
=> [477 merge] VDI.attach2 API and new rpclib library

dbgring/dbgring.ml
Use Bytes where String values are updated.
=> Make dbgring.ml safe-string compliant

dbgring/dbgring.ml
=> Make dbgring.ml safe-string compliant (2)

doc/design/suspend-image-framing-format.md, lib/io.ml, lib/resources.ml, lib/suspend_image.ml, lib/suspend_image.mli, lib/xenops_utils.ml, lib/xenopsd.ml, scripts/qemu-wrapper, suspend_image_viewer/jbuild, suspend_image_viewer/suspend_image_viewer.ml, suspend_image_viewer/view.sh, xc/cancel_utils.ml, xc/device.ml, xc/device.mli, xc/device_common.ml, xc/device_common.mli, xc/domain.ml, xc/domain.mli, xc/emu_manager.ml, xc/stubdom.ml, xc/xc_resources.ml, xc/xenops_server_xen.ml, xl/xenops_server_xenlight.cppo.ml
Continuation of https://github.com/xapi-project/xenopsd/pull/536
=> UEFI: Implement VM suspend/resume

lib/xenops_task.ml
=> Update to newer interface requirements of Task_server

scripts/qemu-wrapper
=> Add OVMF debug print arguments (commented) for convinience

xapi-xenopsd-simulator.opam, xapi-xenopsd-xc.opam, xapi-xenopsd-xenlight.opam, xapi-xenopsd.opam
Dependencies were calculated with dune. We are alsu switching to dune as the build tool, which is more strict.
=> Update opam files

lib/storage.ml, xc/xenops_server_xen.ml
Use PPX Storage interface rather than Camlp4
=> Storage PPX

lib/xenops_server.ml
If an error occurs on the destination, near the beginning of a VM migration,
the destination turned the error into a string that was not turned back into a
Xenops_interface error. This led to cryptic internal errors rather than proper
API errors being returned to the client.
=> CA-297343: Preserve Xenops_interface errors in migration handshake

xc/xenops_server_xen.ml
=> Log when finding an undefined domain type

xapi-xenopsd-simulator.opam, xapi-xenopsd-xc.opam, xapi-xenopsd.opam
=> Update opam files for Opam 2

xc/domain.ml
Remove code that waits for a domain to disappear. The code can only
observe whether a domain disappears as expected but not to anything if
it doesn't. This however, can also be observed from the outside so there
isn't really a good reason to keep this code around.
=> CA-298916 don't wait for domain to disappear

lib/xenops_server.ml, lib/xenopsd.ml
=> Switch to new ocaml-rpc

lib/jbuild, test/jbuild, xc/jbuild
=> Update jbuild files to use 'preprocess pps'

xc/device.ml
Signed-off-by: Mark Syms <mark.syms@citrix.com>
=> CA-299737: set cache=none for disk devices

doc/design/suspend-image-framing-format.md, lib/dune, lib/io.ml, lib/resources.ml, lib/suspend_image.ml, lib/suspend_image.mli, lib/xenops_sandbox.ml, lib/xenops_server.ml, lib/xenops_server_plugin.ml, lib/xenops_server_skeleton.ml, lib/xenops_utils.ml, lib/xenopsd.ml, scripts/block, scripts/qemu-wrapper, suspend_image_viewer/suspend_image_viewer.ml, suspend_image_viewer/view.sh, xc/cancel_utils.ml, xc/device.ml, xc/device.mli, xc/device_common.ml, xc/device_common.mli, xc/domain.ml, xc/domain.mli, xc/dune, xc/stubdom.ml, xc/xc_resources.ml, xc/xenops_server_xen.ml
See https://github.com/xapi-project/xcp-idl/pull/260
=> CP-30222: get ready for merging Guest Uefi into master

lib/xenops_server.ml, xc/xenops_server_xen.ml
This way xapi can report what kind of failure it is to API users.
=>  CA-272180: report failing shutdown commands to xapi

lib/xenops_server.ml, lib/xenops_server_plugin.ml, lib/xenops_server_skeleton.ml, lib/xenops_utils.ml, simulator/xenops_server_simulator.ml, xc/xenops_server_xen.ml, xl/xenops_server_xenlight.cppo.ml
=> CA-308834: backport CA-307829 on havana

lib/xenops_server_skeleton.ml, xc/xenops_server_xen.ml
See https://github.com/xapi-project/xcp-idl/pull/265
=> CP-30508: Expose iommu and hvm flags

xc/device.ml
Signed-off-by: Min Li <min.li1@citrix.com>
=> CA-306416: Get 'num_file_descrs' at runtime instead of hardcode.

scripts/qemu-wrapper, xc/device.ml
=> CA-313265, CA-314034: QEMU serial bug fixes

lib/io.ml
=> XSI-312 CA-289145: Close socket if error occurs when connecting

xc/device.ml
=> CP-31122: Add uuid into parameters to Demu.

lib/xenops_sandbox.ml, xc/device.ml, xc/device.mli, xc/domain.ml
Signed-off-by: Richard Davies <richard.davies@citrix.com>
=> CA-315621 Pass vm_uuid

c_stubs/xenctrlext_stubs.c, lib/xenops_server_simulator.ml, lib/xenopsd.ml, test/test.ml, xc/device.ml, xc/device.mli, xc/xenctrlext.ml, xc/xenctrlext.mli, xc/xenops_server_xen.ml
Also lift pci attach code from xenlight into xenopsd
Signed-off-by: Richard Davies <richard.davies@citrix.com>
=> CP-30136 Allow specifying of pci slot

lib/xenops_server.ml, lib/xenops_server_plugin.ml, xc/device.ml, xc/device.mli, xc/xenops_server_xen.ml
Feature integration to master.
=> REQ-720: Support multiple vGPUs in one VM

.travis.yml, lib/xenops_server.ml
To make sure a domain is not running before destroying its device model,
pause it.
=> CA-315450 pause VM before shutdown

xc/device.ml
This commit make xenopsd work with old Nvidia drivers as followings,
When VM start, xenopsd will check whether the config_file element exists
in the vm metadata, if yes, then xenopsd think it starts the VM in the legnecy
mode and prepare the config_file arguments for demu, otherwise, the
type_id for the vGPU is used. Xapi is responsible to check whether the
installed host driver support multiple vGPU and set the metadata.
Signed-off-by: Lin Liu <lin.liu@citrix.com>
=> CA-322749: Make toolstack work with old Nvidia host drivers

.travis.yml, lib/xenops_server.ml, lib/xenops_server_plugin.ml, lib/xenops_server_simulator.ml, xc/device.ml, xc/device.mli, xc/xenops_server_xen.ml
This series commits adds support for NVIDIA SR-IOV GPUs. It depends on corresponding changes in cen-api.git and xcp-idl.git.
=> REQ-627 set up feature branch

lib/xenops_server.ml, xc/domain.ml
* Don't pass -fork true
* Don't pass -pci_passthrough on VM resume
=> CA-325129 fix flags passed to emu-manager

.travis.yml
https://github.com/xapi-project/xenopsd/pull/658 made us realise we are not testing xapi-xenopsd-xc in Travis, attempt to fix that.
=> Test xapi-xenopsd-xc and xapi-xenopsd-simulator too

xc/domain.ml, xc/domain.mli
=> CA-326317: Xen 4.13 HAP changes

test/test.ml
=> fixup! REQ-627 CA-328215 use pci_passthrough for PV

c_stubs/xenctrlext_stubs.c, lib/xenops_server_skeleton.ml, xc/xenctrlext.ml, xc/xenctrlext.mli, xc/xenops_server_xen.ml
See commit messages for details
=> CP-32446: support CPUID features available only during migration

lib/xenops_server.ml
In particular Domain_not_built.
This fixes a regression introduced by a7563620e89a891c5a454c1d932ac3f12d0c4c3a.
VM_check_state looks at the domain and what actions should be performed.
On an incomplete migration you might get a VM_shutdown as required
action. However VM_shutdown calls VM_pause, which now fails because the
domain was not built yet.
We should let VM_shutdown proceed in this case to finish cleaning up:
if the domain is not built then there is nothing to pause, we ensured
that it is not running.
Signed-off-by: Edwin Török <edvin.torok@citrix.com>
=> CA-330830: ignore errors during VM.pause on hard shutdown

xc/xenops_server_xen.ml
Currently, xenopsd concludes that a VM has PV drivers installed if it has seen
on of the VM's devices (VIFs or VBDs) reach state 4 ("connected"). This is
recorded in the VM's persistent state in field `pv_drivers_detected`, which is
reflected in xapi's `VM.PV_drivers_detected` field, and is not changed until
the VM reboots.
When a VM boots with UEFI, it briefly gets a small VBD attached to it early in
the boot sequence, which has a PV block driver installed and loaded at boot.
Xenopsd will notice this and set `pv_drivers_detected` to `true`, and will not
reassess this state. This is the case, even if the VM's main boot disk does not
have PV drivers installed, and as a result the PV driver status is misreported.
To solve this, xenopsd now considers whether `pv_drivers_detected` must be …
=> CA-328093: Correctly report PV-driver status for UEFI-booted VMs

xc/device.ml
Switching between pass-through and vGPU for Nvidia GPUs lead to host crashes. The root cause were drivers not properly unbound. In particular, all PCI VFs need to be unbound before binding the PCI PF to the pciback driver for passing the GPU to a VM. Futhermore, the pciback driver allocates slots which need to be freed when unbinding the driver.
=> CA-325940 SRIOV switching between vGPU and pass-through

scripts/common.py, scripts/qemu-dm-wrapper, scripts/qemu-vif-script, scripts/qemu-wrapper, scripts/setup-vif-rules
All the changes look safe to me, and much less disruptive than the ones in https://github.com/xapi-project/xen-api/pull/4005
=>  CP-32429: Modernize python2 code (automated)

xc/device.ml, xc/device.mli, xc/xenops_server_xen.ml
Signed-off-by: lippirk <ben.anson@citrix.com>
=> CA-328130 use usb speed to determine bus

scripts/qemu-wrapper, xc/device.ml, xc/domain.ml
=> CA-332811: Manage libxl type record properly

xapi-xenopsd.opam
=> opam: keep up-to-date with xs-opam

lib/xenops_server.ml
* widen de-quarantining to include Intel GPUs (GVT_g)
* limit de-quarantining to GPUs where this is actually required
* make policy for de-quarantining more explicit
These commit are not rebased onto the current master branch because re-basing introduces conflicts but these commits can be merged without conflict.
=> REQ-627 CA-334557 de-quarantine Intel GPUs

scripts/block, xc/device.ml, xc/hotplug.ml
There is also a XAPI part coming in a separate PR, but they do not depend on each other.
Draft, because I need to do more testing.
Explanations in individual commit messages.
=> CP-32863: storage driver domain support

xc/device.ml
The QMP monitoring thread first connects to all existing QMP sockets
that in can find in /var/run/xen. Exceptions here could kill the thread.
This commit makes sure exceptions are caught and logged.
There is still the problem that connecting to a socket could block and
therefore block the entire thread. This could be avoided by implementing
a timeout for the connect() call.
=> CP-33793 make QMP monitoring more robust

cli/xn.ml, lib/xenopsd.ml
Depends on https://github.com/xapi-project/xs-opam/pull/511
=> CP-34942: update for rpclib 8 compatibility

.ocamlformat, lib/xenopsd.ml, vendor/polly/lib/polly.mli, xc/device.ml, xc/domain.ml
Rerun format.
Signed-off-by: Andrew Cooper <andrew.cooper3@citrix.com>
Split out of #172
=> Adjust .ocamlformat to preserve blank lines

lib/suspend_image.ml, lib/xenops_server.ml, lib/xenops_server_simulator.ml, test/test.ml
Requires https://github.com/xapi-project/xcp-idl/pull/319.
=> XSI-555/CA-347560/CA-332779: State management fixes

lib/xenops_server.ml
Depends on https://github.com/xapi-project/xcp-idl/pull/320
=> XSI-555 for Havana

lib/xenopsd.ml, xc/xenops_server_xen.ml
Apply the security fixes to master: https://xenbits.xen.org/xsa/advisory-354.html
=> CA-344431, CA-348217: XSA-354

.github/python-nosetests.sh
There's no need to force updates and these made the runs fail
=> ci: fix python tests

scripts/qemu-wrapper, xc/device.ml
This is a dependency for qemu pq upgrade.
=> CP-33898: Upgrade QEMU to 4.2.1 

lib/suspend_image.ml, lib/xenops_server.ml, lib/xenops_server_simulator.ml, test/test.ml
Backport of https://github.com/xapi-project/xenopsd/pull/722, and https://github.com/xapi-project/xenopsd/pull/732
There's also https://github.com/xapi-project/xenopsd/pull/727, which got reverted in https://github.com/xapi-project/xenopsd/pull/728, so #727 is not included here
=> backport! (stockholm) XSI-555/CA-347560/CA-332779, CA-341518

c_stubs/xenctrlext_stubs.c, lib/xenops_server.ml, lib/xenops_server_plugin.ml, lib/xenops_server_simulator.ml, lib/xenops_server_skeleton.ml, xc/domain.ml, xc/domain.mli, xc/xenctrlext.ml, xc/xenctrlext.mli, xc/xenops_server_xen.ml
=> backport! (stockholm) kdump

scripts/qemu-wrapper, xc/device.ml
These are command line changes to be able to use QEMU 4.2.
There's also a change to the SPEC file.
=> CP-36452: Backport QEMU 4.2 to Yangtze

lib/xenops_utils.ml, lib/xenopsd.ml, xc/xenops_server_xen.ml
Original PR for master https://github.com/xapi-project/xenopsd/pull/739
=> [stockholm] backport CA-351685

xc/device.ml
=> Add mtu to VIF frontend xs tree

scripts/setup-vif-rules
cherry-pick of xen-api.git's 7605423441de4c7e3b1e380320ed6a06518665dc
https://github.com/xapi-project/xen-api/commit/7605423441de4c7e3b1e380320ed6a06518665dc
=> backport: CA-369446: exit with error if add_vswitch_port fails

lib/open_uri_https.ml
Backport of 7b31dec93b144fad8fa569f3688e2634c482bd96 from xen-api.git
The file descriptor for socket /var/xapi/forker/main is leaking. Unexpectedly, Stunnel.with_connect does not close the socket to stunnel which it opens.
=> CA-377824 fix FD leak in xenopsd
